### ISSUE TITLE
There is no sound in the downloaded video.

### ISSUE THREAD

**Issue by Broniy** [libre-tube/LibreTube#1062]
### Describe your suggested feature

You removed the function of converting video to mp4 and mkv format with the last update.Now there is no sound from the downloaded video.Please bring back this feature.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Support for it was removed because its success rate wasn't high and it increased the app's size by more than 100%. Bringing it back is planned, it just requires a different solution that's currently not available. You can use third party android apps to mux audio and video on your own if you need it.
