### ISSUE TITLE
Change background playback.

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#1088]
### Describe your suggested feature

Cancel the background button at the bottom of the player.Instead, add a background playback toggle to the settings.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by IceDBorn** [comment]
I want this for music. Just keep background mode to the player too.

**Comment by Bnyro** [comment]
The background mode is running in a service while the normal player view is part of an activity. It's not possible to run the audio in the background while it being synced with the player view because these would be two independent components with two different lifecycles.
Only thing we can do is to switch to background mode automatically automatically when the display gets turned off or the app gets quitted, but this will result the video to still be at the old state in the player view when resuming the app.

**Comment by IceDBorn** [comment]
@Bnyro Just add a toggle that disables the player view entirely

**Comment by Bnyro** [comment]
Just long press the video in the search and select play in background ;)
