### ISSUE TITLE
Steam directly from YouTube 

### ISSUE THREAD

**Issue by ph00lt0** [libre-tube/LibreTube#1121]
### Describe your suggested feature

Given the following:
1.  Piped's infrastructure isn't always as reliable .
2. Google knows anyway what video's are streamed.
3. If you use a VPN it doesn't really matter whether you stream through a proxy.
4. Using piped shifts trust to that project when it comes to privacy

I would like to see an option to stream directly from YouTube through the app, much like NewPipe does. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by FireMasterK** [comment]
> Piped's infrastructure isn't always as reliable .

I think it's the user's responsibility to choose a reliable instance. There's nothing wrong with the code afaik.

> Google knows anyway what video's are streamed.

But the difference here is Google knows what videos **you** are watching if you don't use the proxy, since with the proxy, all Piped users are seen as one user.

> If you use a VPN it doesn't really matter whether you stream through a proxy.

You'd be breaking music videos by doing so, and YouTube may change this in the future to affect all videos if they so choose to do so. 

> Using piped shifts trust to that project when it comes to privacy

If you can't trust public instances, I'd suggest either self-hosting one or use NewPipe.

**Comment by IceDBorn** [comment]
@ph00lt0 Piped uses NewPipe

**Comment by IceDBorn** [comment]
@ph00lt0 They have similar performance?

**Comment by IceDBorn** [comment]
@ph00lt0 I know the difference between the two, all I'm saying is they offer similar performance. I was using NewPipe for months before I switched to LibreTube and all I can say is that I'm not having any issues with Piped and it's official instance. Streaming directly from Youtube is not an option, it goes against the project's goal.

**Comment by Bnyro** [comment]
I agree with Kavin, he hit the nail on the head!
Apart from that LibreTube is built for working with Piped and rewriting it for the NewPipeExtractor would take multiple weeks and would miss the goal of the project as you can already see in the [README banner](https://github.com/libre-tube/libretube).
