### ISSUE TITLE
Persistently opening dismissed video on app resume

### ISSUE THREAD

**Issue by cjseaslug** [libre-tube/LibreTube#1198]
### Steps to reproduce

Close video from miniplayer
Switch apps or go to launcher
Switch back to Libretube

### Expected behavior

No video playing in miniplayer

### Actual behavior

Miniplayer reopens with dismissed video autoplaying

### LibreTube version

5.0.0

### Android version

12 & 13

### Other details

Happened across 2 different phones (samsung & pixel) on 12 and 13 respectively.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by cjseaslug** [comment]
Hi @Bnyro, sorry to @ you but does "completed" here mean a fix was issued, or that it wasn't reproducible in testing?

**Comment by Bnyro** [comment]
Whoops, sorry, my bad :)
I remember that I accidently closed an issue because I was experimenting with a different GitHub client, that has probably been yours then :)

I'm currently in vacation so I don't really have resources to fix anything, I just had a quick look but couldn't reproduce the issue. I will look into the code once I'm back at home and look whether something can be improved, but can't promise it since the behaviour seems really weird.

Regards

**Comment by rozari0** [comment]
Same issue with 0.5.1

**Comment by emmatebibyte** [comment]
I am also experiencing this issue on my Galaxy s10 running the LineageOS 18.1

**Comment by frutruc** [comment]
Hi, I also observe the same behaviour on my Galaxy A32, Android 12

**Comment by xIUPITERx** [comment]
Any news?

**Comment by Bnyro** [comment]
I wasn't able to reproduce that, so a video showing/reproducing the issue wouldn't be a bad thing!

**Comment by xIUPITERx** [comment]
https://user-images.githubusercontent.com/97352673/197392761-870f047e-082f-4b6b-bebe-68f690118221.mp4

**Comment by Bnyro** [comment]
Could anyone please retry the latest debug version?
