### ISSUE TITLE
High playback speed & audio distortion

### ISSUE THREAD

**Issue by Donkey-Doug** [libre-tube/LibreTube#1262]
### Steps to reproduce

1. Play a video at a high playback speed.
2. Notice the audio does not sound clean, but has some stuttering and is distorted.

### Expected behavior

No distortion

### Actual behavior

Distortion

### LibreTube version

0.5.1

### Android version

12

### Other details

The higher the playback speed, the more noticable the distortion.

VLC and Newpipe do not have this issue, but some other apps (like my gallery app) have a similar distortion issue at high playback speeds. Thus this issue is not unique to libretube and the code/implementation of playback speed might be fine.

I recommend playing the same video on vlc for android and libretube at a very high speed (4x is max speed in vlc for android). Notice the difference in audio quality.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It feels to me the same way when playing normal videos at 4x speed, however when trying slow motion videos like https://piped.kavin.rocks/watch?v=gd89lbviGSs, it doesn't feel like it stutters much.

However, since there's only one way to set the playback speed with the `ExoPlayer`, there's nothing we could really do about it.
