### ISSUE TITLE
Renaming folder, Download to

### ISSUE THREAD

**Issue by rancidfrog** [libre-tube/LibreTube#1282]
Download to does not allow to select Documents folder.
![](https://i.imgur.com/WgnPSv7.jpg)
Allowing user to select folder using OS documentsUI api would be great, as you can also create folder.

Also,
When trying to rename folder in download to, dialog pop-up only shows numbers.
This is probably due to wrong info in type of input allowed:
![](https://i.imgur.com/wRnzixk.jpg)

**Comment by Bnyro** [comment]
Yes, the number thing is a bug because of the wrong input type being set. However, since there were some issues with storage permissions and other downloads related stuff, both these options will be removed in the next update and downloaded videos and audio will be stored inside the app and therefore can be played inside the app.
