### ISSUE TITLE
Release armv8 (64 bit) version on fdroid

### ISSUE THREAD

**Issue by Donkey-Doug** [libre-tube/LibreTube#1552]
### Describe your suggested feature

Release armv8 (64 bit) version on fdroid. Currently only the armv7 version is on fdroid.

### Other details

Pixel 7 and 7 pro dropped support for 32 bit apps.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
F-Droid releases a universal version that's compatible with all architectures.
You probably mean the IzzyOnDroid repo, that's the one that currently only uploads the armv7 version.

@IzzySoft, what is your opinion about providing the `armv7` as well as the `armv8` version at your repo, would that be possible or is there a limit of only one apk per release? Otherwise could you please consider grabbing the `universal` apk instead of the `armv7` which got initially added a few release ago? Thanks in advance :)

**Comment by Donkey-Doug** [comment]
You are correct, it ks the izzy repo that only releases the armv7 versions.

**Comment by IzzySoft** [comment]
There's a per-app limit of 30 MB for my repo. And I cannot handle multiple per-ABI releases. Seeing the universal one is below 15 MB, I could tell my updater to use that (and keep 2 versions). Does it have the same `versionCode` as the corresponding per-ABI build? I've just checked, it has – then everything is fine. Starting with the next release, my updater will switch to the APK file matching `/universal/i` (instead of `/armeabi-v7a/i`) and will keep 2 versions available.

**Comment by Bnyro** [comment]
> There's a per-app limit of 30 MB for my repo. And I cannot handle multiple per-ABI releases. Seeing the universal one is below 15 MB, I could tell my updater to use that (and keep 2 versions). Does it have the same `versionCode` as the corresponding per-ABI build? I've just checked, it has – then everything is fine. Starting with the next release, my updater will switch to the APK file matching `/universal/i` (instead of `/armeabi-v7a/i`) and will keep 2 versions available.

Thank you! <3

**Comment by IzzySoft** [comment]
Simply yell if it didn't work out :see_no_evil: But it should work out fine.
