### ISSUE TITLE
Sign APK before uploading it to TG.

### ISSUE THREAD

**Issue by rozari0** [libre-tube/LibreTube#1567]
### Describe your suggested feature

So every time I want to test debug build, I have to uninstall the old version and then install the new one. And play protect detects this as suspicious every time. (My device is not fully degoogled :| )

I know that isn't something important but this would be nice if you can do this.

### Other details

You can see this action https://github.com/r0adkll/sign-android-release .

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I'm not really into such actions stuff and don't really have the time to read into it and try to get signing of APKs via the actions working. Apart from that signing would have to be done for the GitHub actions CI builds as well as for the telegram builds which would be quite a lot of effort for its final benefits.
So, if anyone wants to invest the time and make a PR for that (you'll need to set the secrets for your accounts manually in order for it to work), I would merge it obviously, but since I think its cost/time effectiveness isn't worth it I'll close it as not planned from my side.
