### ISSUE TITLE
Option for playback gestures (volume & brightness)

### ISSUE THREAD

**Issue by Johnny5sword** [libre-tube/LibreTube#1577]
### Describe your suggested feature

Hi!
I'm already aware of:
- #60
- #62
- #71
- #381
- #545
- #980
- #1310
- #1541

but I think it's better to keep this issue open just in case someone else would like to implement one of the most requested feature.

Related discussion: #854

### Other details

Projects that already have it implemented (Possible reference): 
- https://github.com/videolan/vlc-android
- https://github.com/mpv-android/mpv-android
- https://github.com/TeamNewPipe/NewPipe
- https://github.com/SkyTubeTeam/SkyTube

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I'll also add the "help wanted" label to make it obvious for others that I won't work on this.

**Comment by CodeCubeNeo** [comment]
Any updates on this?

**Comment by xIUPITERx** [comment]
A few ideas I have about the swipe gestures:
1. The size of the fields changes depending on the length of the text (Auto, 0-99%, 100%). In my opinion, the width of the flyout should be fix, regardless of the level or if it's the brightness or volume slider.
2. More options and explanations: Maybe one wants to set the brightness on the left as well as on the right or both gestures swapped. This could be fixed with a small selection menu (swiping left does this, swiping right does that) which would also explain how to use the gestures.
3. Move the sliders further into the middle or all the way to the edge so that they are never on the border of the video to the black bar.

https://user-images.githubusercontent.com/97352673/204056617-8c4397e0-3f3b-4a4b-9172-f8ab2efc03aa.mp4
