### ISSUE TITLE
subtitle size scales with video

### ISSUE THREAD

**Issue by theotheroracle** [libre-tube/LibreTube#1643]
### Steps to reproduce

1. play a video
2. open in full screen
3. the captions are now too large, as they scaled with it

### Expected behavior

the captions shouldn't change size

### Actual behavior

the captions grew and covered the video

### LibreTube version

0.6.1

### Android version

android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by theotheroracle** [comment]
![Screenshot_20221022-175111_LibreTube](https://user-images.githubusercontent.com/20211219/197355404-6ddc4bdd-f767-4a16-bc9d-fa3b0b4ef2a4.png)
![Screenshot_20221022-175055_LibreTube](https://user-images.githubusercontent.com/20211219/197355406-ad1f1ce5-162a-4135-982e-e90f62cb07df.png)

**Comment by theotheroracle** [comment]
compared to newpipe:
![Uploading Screenshot_20221022-175141_NewPipe SponsorBlock.png…]()

**Comment by Bnyro** [comment]
We probably just need to hardcode the font size in order to fix that, gonna have a look before the next update!

**Comment by Bnyro** [comment]
The size should be the same now for fullscreen and the normal player, it might just look smaller because of the increased video size.
I couldn't find an other solution to keep the size consistent over screen rotation or a changed size of the video when entering fullscreen in vertical mode. I agree that the current solution is not the best one, adding our own font size preference would probably be a good idea.
Please feel free to open an issue for it as it's really hard to keep an overview of possible changes when you open issues under already closed issues :)
