### ISSUE TITLE
reverse button in playlist page

### ISSUE THREAD

**Issue by ydqsbfsyi** [libre-tube/LibreTube#1812]
### Describe your suggested feature

Sometimes we want to play the oldest video first in a playlist, but youtube lay it out the other way; sometimes we need play the recent video first but youtube shows the oldest first. That's awkward when a playlist is huge, and we can not do anything since it's usually somebody else's playlist. 
Given that Libretube clones every playlist to our own, it would be nice to have a "reverse order" button inside any playlist, which can deal with both the above 2 situations.
Could you please consider this?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's currently a bit hard since we can't fetch the whole playlist all at once, it requires multiple requests, one per 20 videos.
Hence I don't think we can really add a button for it in the playlist view.

However, the playing queue already fetches the whole playlist in the background after starting to play the first video, so a button to reverse the playing queue could be added which would somehow solve the issue as well in my opinion. Would you be okay with that?

**Comment by ydqsbfsyi** [comment]
> However, the playing queue already fetches the whole playlist in the background after starting to play the first video, so a button to reverse the playing queue could be added which would somehow solve the issue as well in my opinion. Would you be okay with that?

That sounds wonderful. Thanks.

**Comment by ydqsbfsyi** [comment]
@Bnyro Marvellous! So handy. I appreciate your time and effort.

**Comment by Bnyro** [comment]
> @Bnyro Marvellous! So handy. I appreciate your time and effort.
>
Awesome that you're happy with it :)
