### ISSUE TITLE
Can't select backup file on Android 9.

### ISSUE THREAD

**Issue by rozari0** [libre-tube/LibreTube#1888]
### Steps to reproduce

1. Open LT 
2. Go to advanced -> Backup 
3. Now try to restore 

### Expected behavior

Should able select files and restore preferences.

### Actual behavior

Can't select any file.

### LibreTube version

0.7.1

### Android version

Android 9

### Other details

I've sent a video before in matrix. :)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The reason is that your system doesn't detect mime types properly, we're currently filtering for JSON files which your phone doesn't seem to recognize. 
So in the end we would have to allow unknown file types as well to make it work for you, but that might cause confusion for others too, so idk yet what a good way could be.

**Comment by rozari0** [comment]
Works fine if try to use other file manager. xD
Why didn't I try this? -,-

**Comment by Bnyro** [comment]
That's awesome :tada:
