### ISSUE TITLE
PIP stops while clicking links.

### ISSUE THREAD

**Issue by quik-dusk** [libre-tube/LibreTube#2022]
### Steps to reproduce

1. Play video.
2. Click any link in the description or comments sections that redirects to open browser

### Expected behavior

The running video should turn to PIP mode.

### Actual behavior

PIP mode stops although video plays in background.

### LibreTube version

0.8.0

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by RafaelsRamos** [comment]
Hey 👋 I took some time to analyse this ticket.

Currently, this is  the behaviour we have:

https://github.com/libre-tube/LibreTube/assets/40279132/376be321-5aa7-4638-87e6-213b44c5aa7f

This behaviour is somewhat similar to what YT does. The difference is that they open a WebView instead of redirecting to the browser:

https://github.com/libre-tube/LibreTube/assets/40279132/aa194cef-6265-4aeb-82a7-4b66dfbfd725

I went ahead and tried to enable PiP after redirecting to outside the App, and this is the result:

https://github.com/libre-tube/LibreTube/assets/40279132/19d07b55-6aa4-42d8-b4b6-0d84f5d8d3aa

### Discussion

Having tried both approaches extensively, in my opinion, the current behaviour we have is best. Mainly because, most times, users press on a link and then want to go back to the video. If we apply this change, that flow would no longer be natural since the user would have to re-open the video by pressing the PiP or through the persistent notification.
