### ISSUE TITLE
Replace 'Open with' button with 'Pop-Up' button.

### ISSUE THREAD

**Issue by rozari0** [libre-tube/LibreTube#2069]
### Describe your suggested feature

If someone presses the pop-up button, LT should play video in PIP mode. It's kinda uneasy to open in pip by pressing the back button.
As nobody use 'open with' button anymore, it can be replaced with this.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
In second thought I would rather have a button for ``background playback`` singe you can start ehe PiP simply by closing the app

**Comment by Bnyro** [comment]
> In second thought I would rather have a button for `background playback` since you can start the PiP simply by closing the app. And thanks to the improved PiP I cant find a way to start the background playback.
>
Just press the `audio` button to start the background playback?

**Comment by xIUPITERx** [comment]
>Just press the audio button to start the background playback?

Not really, before that you could return to the video and watch it again, with the ``audio`` button you can't switch back without losing progress until #1157 is completed.

**Comment by BlackLight** [comment]
> As nobody use 'open with' button anymore, it can be replaced with this.

cit. needed

I used to use it to open the raw video URL in external players, which in turn allowed me to do things like casting to Kodi, Chromecast, VLC servers, queue for download on a server etc.

Now I'm kind of stuck on being able to watch videos only within the app.

**Comment by BlackLight** [comment]
Is it possible through any in-app mechanisms? As of now the Share button shares the Piped/YouTube URL, not the raw video.

**Comment by BlackLight** [comment]
Why this decision? It's really pointless to me to have a YouTube player that can only play videos in-app and doesn't provide a possibility to share the stream with other players.

I guess I'll either make a fork of this app that reverts this change, or uninstall it and find an alternative.

**Comment by rozari0** [comment]
> Why this decision? 
Because it's not a feature that users actually uses. 

> It's really pointless to me to have a YouTube player that can only play videos in-app and doesn't provide a possibility to share the stream with other players.

I don't think other alternative has/had this feature. So go on and try other alternative.

**Comment by BlackLight** [comment]
> I don't think other alternative has/had this feature. So go on and try other alternative.

They actually do. NewPipe supports opening videos in an external player, but I'm not that keen in using it because it doesn't synchronize with a Piped instance and all the subscriptions and playlists live on the device.

And Kodi has even a plugin that makes it mimic a pairable device that can be visible through the YouTube app directly (but I don't want to use the YouTube app at all).

IMHO the ability to play videos on a device with a larger screen than a phone is quite crucial to any video player. That's why I'm so confused when I hear "we removed it because people didn't use it" (I wonder how many people were asked).

Forking LibreTube, reverting this change and maybe improving the logic for transcoding would perhaps be the most logical steps for me.
