### ISSUE TITLE
DASH vs HLS

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#2076]
### Steps to reproduce

If HLS is activated the video buffers way faster than with DASH (3-4 times)

### Expected behavior

Should load it equally fast (same internet connection)

### Actual behavior

Different speed

### LibreTube version

latest debug

### Android version

Android 12 One UI 4.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Hmm, that's weird, for me DASH is about 2 or 3 times faster in most cases and plays almost instantly!
However, that might be caused by your device in specific because the feedback so far about it has always been positive. 
Since you still have the option to use HLS, there shouldn't be a reason to not do so!

**Comment by FireMasterK** [comment]
DASH has shown significant speed improvements over HLS for me. HLS is also limited to 1080p 30fps, DASH doesn't have any resolution limits.
