### ISSUE TITLE
Suggesting to apply theme to more UI elements

### ISSUE THREAD

**Issue by tvnmguy** [libre-tube/LibreTube#2079]
### Describe your suggested feature

Taking 'Groovy green' as an example here;

![IMG_20221126_154509](https://user-images.githubusercontent.com/116799295/204085528-007ede30-c51f-495d-a81f-9d6b6c58b4cb.jpg)

![IMG_20221126_161625](https://user-images.githubusercontent.com/116799295/204085535-246c9312-cb68-422b-98d4-2c6770d8874f.jpg)

![img_2022_11_26_16_02_56](https://user-images.githubusercontent.com/116799295/204085546-112c9ead-17dd-4725-b3e2-3bb90d06b49e.jpg)

![img_2022_11_26_16_10_28](https://user-images.githubusercontent.com/116799295/204085555-aa149e3e-02b3-4922-819d-e1c764d49c68.jpg)

![img_2022_11_26_16_07_29](https://user-images.githubusercontent.com/116799295/204085572-10445ab9-0b16-456e-be00-415a591b84c4.jpg)

![img_2022_11_26_16_06_59](https://user-images.githubusercontent.com/116799295/204085586-1caf0940-e904-4403-bb7c-7a8e976733aa.jpg)

![IMG_20221126_161102](https://user-images.githubusercontent.com/116799295/204085595-1d5df554-8223-4456-a976-08276486a997.jpg)

### Other details

![IMG_20221126_161559](https://user-images.githubusercontent.com/116799295/204085599-f825ecd3-2c07-4f97-b319-f430abba209e.jpg)

![IMG_20221126_161226](https://user-images.githubusercontent.com/116799295/204085605-2f34452e-3745-43ce-b75b-4fda7ff65696.jpg)

![IMG_20221126_161207](https://user-images.githubusercontent.com/116799295/204085612-56f30df9-c2c1-472c-86e2-d1d3b01f1dd1.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I'm not really a fan of using so many different colors for most things. Anyways it's not possible to do so for dialogs because they're provided by the `MaterialAlertDialogBuilder` which doesn't support that. 
For a slightly better appearance of the subscription button, there is already #1916, maybe changing the color of the subscribed button within that would be a good idea too, although probably with less contrast than your sketch uses.
Anyways thanks for your efforts into that <3
