### ISSUE TITLE
Option to allow only swipe gestures for brightness or volume

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#2084]
### Describe your suggested feature

A few ideas I have about the new gestures:
1. The size of the fields changes depending on the length of the text (Auto, 0-99%, 100%). In my opinion, the width of the flyout should be fix, regardless of the level or if it's the brightness or volume slider.
2. More options and explanations: Maybe one wants to set the brightness on the left as well as on the right or both gestures swapped. This could be fixed with a small selection menu (swiping left does this, swiping right does that) which would also explain how to use the gestures.
3. Move the sliders further into the middle or all the way to the edge so that they are never on the border of the video to the black bar.

### Other details

https://user-images.githubusercontent.com/97352673/204056617-8c4397e0-3f3b-4a4b-9172-f8ab2efc03aa.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
Also have an option to disable Pinch to Zoom.

**Comment by Kruna1Pate1** [comment]
1. Will fix that
2. I think that would be too much overhead and I think most users prefer using this configuration. However, we can think about using a single gesture like only brightness or volume.
3. Since It is attached to the border and margin is given from the end, probably it will vary from device to device.
e.g. for me it's like,

![Screenshot_2022-11-26-22-08-26-16_7af1185115278aeb9699bfd161691b7e 1](https://user-images.githubusercontent.com/33123061/204099448-e1fb490e-15da-48cd-8b04-485272e3caab.jpg)

**Comment by xIUPITERx** [comment]
3. Could you make the spacing to the border depending on the aspect ratio?

**Comment by Kruna1Pate1** [comment]
> Could you make the spacing to the border depending on the aspect ratio of the video?
surely will try that.

**Comment by Bnyro** [comment]
I neither think it makes sense to add an option to only enable one of the gestures (as you can just not use the one gesture if you don't want to) nor allowing user's to change the position of the controls, thus closing.
