### ISSUE TITLE
Screenshot button on the player interface 

### ISSUE THREAD

**Issue by GET100PERCENT** [libre-tube/LibreTube#2197]
### Describe your suggested feature

After version 0.8.0 libretube has implemented many essential features on the player interface.

Often it is required to take a screenshot of important information showing in the video when watching some online classes or some documentary videos even in any video having some important information.

When one tries to take a screenshot, it is required to pause the video, scroll the quick tile tray and then select the screenshot tile, which is not easier.

It will be easier if the player screen has a screenshot button on the middle of the right edge of player screen. 

By this, on a single click the current frame can be captured as a screenshot, which is very useful.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
1. I don't think there's a system API for it.
2. If there was one it required additional permissions.
3. You can just take a screenshot by pressing a key combination, for me the power and the volume down button at the same time.

**Comment by GET100PERCENT** [comment]
Okay 👍

**Comment by 5wHN28Dg** [comment]
Okay hear me out I have a somewhat similar proposal but better, taking a screenshot is a lossy process and in many cases, I'll end up having unwanted and unnecessary black bars in the screenshot so what if I was able to pause the video then tab on the screenshot icon in the player and instead of the app taking a screenshot it will extract the paused frame from the video and save it in a lossless format (PNG or jpeg xl) thus avoiding the 2 cons of taking a screenshot, what I'm proposing isn't something unheard of after all I can already do this for a local file with an FFmpeg command or use [this video player](https://play.google.com/store/apps/details?id=com.precisecontrol.videoplayer.free)

I wouldn't dare to say that this feature is a must-have but it is a nice to have so I really hope you will consider assuming that it is possible to implement
