### ISSUE TITLE
Option to remove watched videos from playlist.

### ISSUE THREAD

**Issue by Lemon-in-Suspense** [libre-tube/LibreTube#2525]
### Describe your suggested feature

Please add the option to remove watched videos from playlist (just like that in the YouTube app).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I think this would be sorta useless, playlists are made to be watched/saved for later, so why would you want to automatically remove videos from it?
Apart from that the implementation would be a bit messy when using with a Piped account since we would need to fetch all videos from all your playlists, just wouldn't make sense for that.
