### ISSUE TITLE
[invalid] feature suggestion - cache results, refresh on demand

### ISSUE THREAD

**Issue by ghost** [libre-tube/LibreTube#2579]
### Describe your suggested feature

https://user-images.githubusercontent.com/415238/210582251-19bfd0f5-ef31-4933-b17b-711a59a6c8f5.mp4

<hr/>

avoid re-fetching data when users switches back and forth from in-app tabs,  
or switching app from background to foreground.  

benefits:  
- reduced amount of requests to PIPED API.
- app feels faster for the user.

drawbacks (depending on how it is implemented):  
- increased RAM consumption.

(may be 'feature flag' protected, to preserve current behavior).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Storing all requests in the app isn't really a good idea since the UX would suffer from that sometimes, e.g. when playlists don't seem to sync with the Piped account because they don't get refreshed automatically.
However, as the subscriptions feed often has long loading times, there's an option to load it in the background under the advanced settings which works as you described. Implementing that for other parts of the app doesn't really make sense in my opinion.
