### ISSUE TITLE
Personalised List of Videos on Home Page

### ISSUE THREAD

**Issue by XelXen** [libre-tube/LibreTube#2612]
### Describe your suggested feature

LibreTube is continuously improving except in one area, which is user experience. Users want a personalized feel from the app they are using. YouTube regularly collects user data and then creates a user experience that is very personalized. LibreTube eliminates the user data collection part but doesn't create a personalized user experience.

**Currently, Libretube fetches a Home page JSON from Piped Instances that gives a list of videos to be displayed, this provides a home page but one that does not care about user interests. I think LibreTube should store recommendations of videos that the user watches and save the recommendations of the last 10 to 20 videos like that. After being stored, Libretube can select a few random videos from the saved recommendations list to be displayed on the home screen**

This way LibreTube won't create a load on the server and will have a privacy-centric, localized, and personalized UX,

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by d4f5409d** [comment]
Oh Jesus Christ, why do you want to destroy the philosophy behind LibreTube? Didn't you hear customizing content recommendations can be very dangerous?
https://www.youtube.com/watch?v=prx9bxzns3g

On the other side, this is not implementable, because then we would cut off privacy as a whole. LibreTube would have to collect data, otherwise, it couldn't recommend videos. If you want an experience like that, search for and subscribe to the right channels, learn yourself, what you do like, what you do not, ask your friends about content creators, et cetera. Otherwise then unfortunately this place is not where you belong.
Teach yourself, people, please.

**Comment by adam-devel** [comment]
> this is not implementable
It is implementable
> because then we would cut off privacy as a whole
No this has nothing to do with privacy, you misunderstood the issue
> LibreTube would have to collect data, otherwise, it couldn't recommend videos.
Libretube is just a piped client, it can't "collect data" if the server doesn't collect data, and this is not what the issues is asking for anyways, libretube already show recommendations under videos, these recommendations that are **already visible** can be put separately in a recommendations tab, that's the whole idea, if this compromise privacy then libretube is already compromising privacy
> If you want an experience like that, search for and subscribe to the right channels
Very often people find channels they like through recommendations
> learn yourself, what you do like, what you do not
irrelevant
> ask your friends about content creators, et cetera
Implementing this idea doesn't prevent you from doing that, it just give you an additional useful option to find channels your friends don't know about 
> Otherwise then unfortunately this place is not where you belong.
You are not the ruler of "this place"

**Comment by itexpertshire** [comment]
I am very much supportive of this feature. This feature will bring life to home page. For now I am experimenting in my local version. My approach is as follows,
1. Store some keywords from watched videos 
2. Periodically search piped instance to fetch top 3 videos  related to watched keywords
3. display the videos in home page as new section recommended videos

Not sure if this approach will fit for all

**Comment by Mr3Sepz** [comment]
I think a part of this could be implemented sort of "manually" and split it into 3 categories:
- New
- Oldies
- Discover

I am no programmer, but this system seems to me doable, since it only needs to know who you subscribed to and needs to see what gets recommended to a certain video (for Discover).

### New
Why not let the user put some of the channel you subscribed to into different levels/ranks? 

For example I could therefore put special channels I really like, but upload irregularly and not often in a high level and therefore see their videos prominently.

That way I dont miss these to me special videos, that would otherwise get drowned in my subscription feeds, by channels that upload more regularly.

As a default channels could be sortet based on how often they upload.

### Old
Also picking random old videos of channels I suscribed to could be helpful, especially when i subscribe to them new. 

But here the user also should be able to place channels into this category with levels or something, since I have channels I know almost every video of. And having this section cluttered with videos I already know, makes it useless.

### Discover 
Just pick a random video of a channel I subscribed to. Then see what gets recommended to that video and pick something from a channel I am not currently subscribed to. 

I think it would also be smart to let the user choose or opt out of recommendations from special channels. 
If I follow this one sports channel, but dont want any more sport video recommendation it would be nice to say: no recommendations based on that channel.

**Comment by Bnyro** [comment]
Our current home tab has a lot of capabilities now, and it's configurable what it actually shows. That allows you to quickly navigate to videos you recently started watching, that are trending or that content creators you subscribed to recently uploaded.

There's still no plan to save related videos to your browsing behavior and mix them with an algorithm. It would require a lot of additional network traffic, way larger app data size due to the need of storing everything in the database and potentially could result in negative consequences for the watching behaviour of users.
