### ISSUE TITLE
constant Chapter name in player

### ISSUE THREAD

**Issue by NeeRaj-2401** [libre-tube/LibreTube#2850]
### Steps to reproduce

1. Play video having chapters
2. navigate between chapters

### Expected behavior

Correct chapter name as in description and dialogue.

### Actual behavior

only first chapters name is visible in player 

### LibreTube version

0.11.1

### Android version

Android 12

### Other details

also after PR #2848  , in portrait mode when clicking on chapter name. the lanscape mode dialogue is popping up. which was not intended [mentioned here](https://github.com/libre-tube/LibreTube/pull/747#issuecomment-1179723330)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by NeeRaj-2401** [comment]
to be fixed 
1. chapter name in player
2. chapter dialogue pop-up in portrait

**Comment by Bnyro** [comment]
it was mentioned in [Always use the chapters dialog as on title click action](https://github.com/libre-tube/LibreTube/pull/2848/commits/7b16580cb152b3574b6e43eb3e59dbcdc2eec2db), the issue is caused by https://github.com/libre-tube/LibreTube/pull/2848/commits/93b073a3577f64393c8cf0f4655015ace33ae86b
