### ISSUE TITLE
Screen stays on when video is paused (no timeout)

### ISSUE THREAD

**Issue by Hujair** [libre-tube/LibreTube#2877]
### Steps to reproduce

pause the video

### Expected behavior

Screen should timeout if video is not playing for X minutes 

### Actual behavior

Screen stays on until battery runs out 

### LibreTube version

0.11.1

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by PhilC813** [comment]
I think this issue is back in the current app version, v0.30.0. If I pause a video or if the video has ended, the screen never turns off, even though my Android display timeout is set at 2 minutes. The issue persists after a reinstall of LibreTube, and is unique to LibreTube.

My device is a OnePlus 13 running the latest version of LineageOS, v23.2, based on Android 16 QPR2.

Would it be possible to reopen the issue?

**Comment by Bnyro** [comment]
Please open a new issue instead, that's likely unrelated to this issue here.
