### ISSUE TITLE
Player fade out when moving progress bar

### ISSUE THREAD

**Issue by MatsG23** [libre-tube/LibreTube#2963]
### Steps to reproduce

1. Play any video
2. In the player controls, try to move the video time progress bar for like 5 seconds

### Expected behavior

Whenever you move the progress bar a bit, the timeout for fading out the player controls should be reset so that the player controls will not fade out when you do not expect it to.

### Actual behavior

The player controls fades out after the default timespan.

### LibreTube version

0.11.1

### Android version

Android 13

### Other details

Bug discovered in https://github.com/libre-tube/LibreTube/issues/2855

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by ehea617** [comment]
Moving my issue https://github.com/libre-tube/LibreTube/issues/2976 to here as I didn't notice this one:

### Steps to reproduce

1. Open a video in LibreTube
2. Tap on the timeline of the video and begin scrubbing to a different time in the video
3. Depending on how much time is taken, the timeline and video preview will disappear making it difficult to navigate to a specific time in the video

(See attached screen recording)

### Expected behavior

The timeline and video preview will stay visible while scrubbing.

### Actual behavior

The timeline and video preview disappears after a short period of time making it difficult to scrub to a specific time in a video, especially for longer videos and livestreams.

### LibreTube version

0.11.1

### Android version

Android 13

### Other details


https://user-images.githubusercontent.com/12926544/216849044-df97be80-21ba-47ee-8348-61d1f51f363e.mp4
