### ISSUE TITLE
Load Home instead of Subscriptions on open

### ISSUE THREAD

**Issue by SalusVF** [libre-tube/LibreTube#3121]
### Steps to reproduce

1. Go to Appearance>Navigation Bar>Order and set Subscriptions as the first tab to show. 
2. Uncheck the Home tab.
3. Restart LibreTube.
4. On start it won't show the Subscriptions feed.

### Expected behavior

I would expect to load the main (first) tab of the navigation bar on application open. 

### Actual behavior

On open it loads the _Home_ page instead of subscription feed, even though _Home_ not present (settings checkbox unmarked)

In this picture below you can see I have no _Home_ tab but still LibreTube loads _Home_ on open instead of the Subscriptions feed.

![Screenshot_20230219-102920](https://user-images.githubusercontent.com/53519166/219940125-23a0f0f3-bad9-468d-8acc-fd0311022d7a.png)

### LibreTube version

0.12.0

### Android version

13

### Other details

Maybe another solution would be to add the option to select the Tab to load on open in the settings menu.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment]
The start tab can be selected via the small house icon.

**Comment by xIUPITERx** [comment]
I'm not sure if this shouldn't be moved to a separate setting, as it seems to cause a lot of confusion for new users.

**Comment by Bnyro** [comment]
I don't think that would be a good idea because that will make managing the tabs take more time because you need to navigate through multiple options.

**Comment by SalusVF** [comment]
> The start tab can be selected via the small house icon.

Oh god... You are right. I didn't even noticed that was a clickable icon... 
Now it works as expected! Thank you. 

Is there any documentation on those things? There are some things that are kind of hidden or non-intuitive.

**Comment by shuvashish76** [comment]
Too many requests for the already existing feature. I don't think it's a coincidence that so many users missed this feature including me. I think the issue is _activated home icon color_ is same as our _other greyish icons_ which leads to assumption that it's just an icon with no functionality.

I suggest to fill the activated home icon colour to accent one to make visually clear for users.

![LT_light](https://github.com/libre-tube/LibreTube/assets/48226312/70aa1444-6515-41a0-ba30-92998d6e5cee)
![LT_dark](https://github.com/libre-tube/LibreTube/assets/48226312/a02900f0-b286-4179-8850-c8a7c693b54d)

**Comment by Bnyro** [comment]
Sounds like a good idea, please open a new issue for that.
