### ISSUE TITLE
remove image placeholders in data saver

### ISSUE THREAD

**Issue by itsmmt305** [libre-tube/LibreTube#3213]
i dont want the images to load anywhere in the app. but when i enable data saver to not load images, it only hides the images, not remove the placeholders. resulting in an abomination of empty spaces everywhere

![Screenshot_2023-03-01-18-32-19-682_com github libretube](https://user-images.githubusercontent.com/94820934/222148399-8cb9f6c6-8d02-43ea-8832-73c039c5c291.jpg)

if you just remove these image placeholders, not only will the text be abridged in less space, the items look sleeker, it will enhance the layout as well. we will get more links in less space.

### Other details

the placeholders occur everywhere - ``home``, ``subscriptions``, ``search page``, ``watch history`` and ``playlists``. 

> however i feel ``downloads`` page must have placeholders still with the images intact even in data saver. 
if needed, you could add an outline to the title text in order to visually seperate the items and maintain clarity.

please do consider this suggestion. thanks!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
When removing the place holders, the duration of the video would either not be visible either anymore or just flying around somewhere. Apart from that it would looks very squeezed without the placeholders since each result would only consist of a very few lines then.
Thanks for the suggestion, however there are currently no plans to realize that in the app.
