### ISSUE TITLE
Tab resets on switching to another

### ISSUE THREAD

**Issue by eightyy8** [libre-tube/LibreTube#3215]
### Steps to reproduce

1. Select a navigation tab
2. Use that tab by opening something
3. Switch to another tab
4. Switch back to original tab
5. Tab forgets place and refreshes/resets itself

Minor yet extremely annoying for any user's flow on the app.

### Expected behavior

Switching to another tab should not refresh previous tab, and LibreTube should remember it's previous state.

### Actual behavior

Instead it forgets it's state and resets whatever you had open.

### LibreTube version

0.12.0

### Android version

Android 13

### Other details

It also refreshes when you open in the tab and go back within the tab.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
By enabling "load feed in background" in the advanced options the feed will be kept when switching between tabs. 
There are no plans to prevent the reloading for the other tabs as well since that's mostly the expected behavior. E.g. if you add a video to a playlist and go to the library, you expect the video to be added to the playlist in the library.
The home page also gets refreshed as it contains bookmarks and playlists which are matter to change multiple times during user sessions.
