### ISSUE TITLE
[Discussion] Add a more detailed privacy policy

### ISSUE THREAD

**Issue by ghost** [libre-tube/LibreTube#3268]
### Describe your suggested feature

Related to #2379

I see that your Translate you app now has [a privacy policy](https://github.com/Bnyro/TranslateYou/blob/master/PRIVACY%20POLICY.md). In this issue I would like to discuss the improvement of the privacy policy of LibreTube.

> The LibreTube project aims to provide a private, anonymous experience for using web-based media services.

Ok, please elaborate?

> Therefore, the app does not collect any data without your consent.

But I am using the app and the instances, so the app now collects my data? Or does it? What data is collected, where and when? What about the Piped instances? And actually, this sentence is all there is, next words are the disclaimer 

According to your comment in #2379,

> [...] as long as you don't log in with a Piped account no data is stored at all.

I think this has changed recently since there are now local playlists? And both local playlists and subscriptions are some kind of data, so I think the privacy policy should make the answers for the following questions clear:

- What data does the app itself store? (Subscriptions, local playlists, bookmarked playlists, settings, anything else?)
- Does the app itself has any kind of telemetry, analytics tracking or user profiling? If so, how is this data handled and who can access it?
- Where does the app fetch a list of instances from?
- What do the Piped instances do when you request a local feed update or load a local playlist? Do they track the users some way, keep the logs of accessed information, etc? Is this information unique to each instance or is there a standard policy all instances (which are included by default) follow? Could you add an example privacy policy of some instance or of a universal one if there is such?
- What changes when you use a Piped account? What happens when you delete it (if there were logs, are they also deleted?)
- Is using LibreTube truly makes you anonymous for YouTube? (Probably not but there should be an explanation why)

I would like to discuss this so that we could make a better privacy policy to make the app and the user experience even better

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I will do my best to answer all the questions once I find time for it, however writing the actual privacy policy is nothing I'm good at so I'd be happy if someome could take me off that burder and ask questions if there are any (after your previous ones got answered). So thr issue is pinned now looking for any suggestions what should be included and for people willing to write the privacy policy itself based on it.

**Comment by heartlog** [comment]
> I will do my best to answer all the questions once I find time for it, however writing the actual privacy policy is nothing I'm good at so I'd be happy if someome could take me off that burder and ask questions if there are any (after your previous ones got answered). So thr issue is pinned now looking for any suggestions what should be included and for people willing to write the privacy policy itself based on it.

How about i give an template? 
You can modify it accordingly.

**Comment by heartlog** [comment]
@Bnyro you can check pull request #3280

**Comment by heartlog** [comment]
> @heartlog the policy in your PR implies that LibreTube collects user data and there is also no in depth explanation to what happens to it, so there are no answers to the questions above. I think it's better to wait until @Bnyro answers the questions and then we could try to rewrite it to something more legally correct

As i mentioned Maintaner can make changes in PR i given.. including @Bnyro
The changes can be made by them if required.

**Comment by Bnyro** [comment]
>  What data does the app itself store? (Subscriptions, local playlists, bookmarked playlists, settings, anything else?)
> 
All data the app itself stores can be exported within the `Backup and Restore` section. These are watch history, watch positions, search history, settings, bookmarked playlists, local subscriptions and local playlists. Some of them can be disabled by the user and thus won't be stored anymore.
The only other thing that is being stored is a list of all your downloads, however as soon as you delete a downloaded video it gets deleted from the app's database too.
>  Does the app itself has any kind of telemetry, analytics tracking or user profiling? If so, how is this data handled and who can access it?
> 
LibreTube itself doesn't contain any kind of telemetry or analytics as I do really hate how some apps handle it without asking users for the permission. There won't ever be such a thing in LibreTube. LibreTube also opts out from usage data analytics that could be done by some libraries, so there's no usage data or telemetry tracked in the whole app!
>  Where does the app fetch a list of instances from?
> 
The list of instances is being fetched from `piped-instances.kavin.rocks` by default, as fallback we use `instances.tokhmi.xyz`. The first one is official and thus should be trustworthy, the second one is needed as `piped-instances.kavin.rocks` is blocked in some regions so a fallback is needed, e.g. for Iranian users iirc.
>  What do the Piped instances do when you request a local feed update or load a local playlist? Do they track the users some way, keep the logs of accessed information, etc? Is this information unique to each instance or is there a standard policy all instances (which are included by default) follow? Could you add an example privacy policy of some instance or of a universal one if there is such?
> 
Local feed updates are done by submitting a list of channels IDs to the Piped instance which then returns a list of videos from these channels. There is some caching being done on Piped's server side, however the process is not logged through Piped.
Local playlists are stored inside the app and **not** refetched when you visit the playlist, so Piped won't ever know which videos your private playlist contains.
There's nothing such as a universal privacy policy. However, all instances have their own privacy policy as far as I know, a good example would be the one from [whatever.social](https://whatever.social/privacy) for example. What an instance actually logs through their web server (e.g. nginx) depends on the configuration of the instance, therefore having a look at their privacy policy might always be a good idea.
>  What changes when you use a Piped account? What happens when you delete it (if there were logs, are they also deleted?)
> 
Piped accounts get deleted completely when you decide to do so, there's no history kept. It's like you never even had an account, so you should be safe on that site.
>  Is using LibreTube truly makes you anonymous for YouTube? (Probably not but there should be an explanation why)
> 
Since LibreTube only connects to Piped instances and not to YouTube's servers directly, there's a huge benefit in privacy as there's always a Piped server in-between you and Big G. However, with that you somehow also shift trust to the owner of the instance you're using. Piped doesn't log any user specific data like IPs, but you can never be 100% sure what the instance owner is doing. But even if an instance owner logged something, they had way less data than YouTube had from you if you used it directly as LibreTube doesn't send any telemetric data to the instance's server.

I hope that somewhat answers the questions and will be helpful for extending the privacy policy and give users a deeper understanding of LibreTube works behind the scenes.

**Comment by heartlog** [comment]
@Bnyro  Shoud i change Privacy policy According to given info or you'll be doing it ?
If yes then I will update it just in case and review and modify it.

**Comment by Bnyro** [comment]
It'd be awesome if you could just continue updating it :)

**Comment by heartlog** [comment]
Great👍
