### ISSUE TITLE
Adding the Ability to Insert New sponsorblock Segments to Videos

### ISSUE THREAD

**Issue by heartlog** [libre-tube/LibreTube#3446]
### Describe your suggested feature

To add a new segment to a video, Revanced provides a convenient feature that could prove useful if it were implemented in LibreTube.

To accomplish this, we could potentially utilize a module from the Revanced patches GitHub repository. Specifically, the [`app.revanced.patches.youtube.layout.sponsorblock.bytecode.patch`](https://github.com/revanced/revanced-patches/tree/main/src/main/kotlin/app/revanced/patches/youtube/layout/sponsorblock/bytecode/patch) module could be helpful.

Although I am not intimately familiar with Kotlin, I can assure you that this module should simplify the process and provide a professional solution for implementing this feature.

Please let me know if you have any further questions or concerns, and I'll do my best to assist you.(somehow)

Layout: (You can use same as Revanced)

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Currently, we're always having Piped servers in between when interacting with SponsorBlock. The Piped backend currently does not support creating new SponsorBlock segments, thus I don't feel like adding support for it since that would make the user connect to an other server without them acknowledging that. Moreover, I don't feel like we have any space left in the player UI currently.

The ReVanced implementation does not matter to us as LibreTube is not meant to copy the behavior of other similar apps. The documentation about at the SponsorBlock repo is public anyways.

**Comment by tiwna16** [comment]
Yeah.That's what I also want.Doesn't matter if it is already available in other apps or not.The main objective of mine is that many times video segments are not reported by Sponserblock Users.So,If we can add Segments from our side also then it will not only be helpful to us but also to other LibreTube users.Please make an opposition for this in the current UI.It will very useful as we already see how much helpful sponserblock feature is.
