### ISSUE TITLE
Update app on fdroid

### ISSUE THREAD

**Issue by muhammad-ans** [libre-tube/LibreTube#3484]
### Describe your suggested feature

App is not updated on fdroid fdroid version is at 0.12
but github version is 0.13.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by muhammad-ans** [comment]
But the problem is  current fdroid version has this bug https://github.com/libre-tube/LibreTube/issues/3185#event-8607731430, I'm unable to backup the history and neither i can update the app.

**Comment by Bnyro** [comment]
According to the F-Droid build status, F-Droid did detect there's a new version but didn't attempt to build it yet. 
Version 0.12.1 didn't appear there at all because gradle version 7.6.1 didn't seem to have a valid hash available (?)
F-Droid had some issues recently though that prevented any apps to update.
So all we can do is wait and look for help by an F-Droid maintainer if there are no updates in the next days.
