### ISSUE TITLE
Force Landscape Setting

### ISSUE THREAD

**Issue by Theblackcat98** [libre-tube/LibreTube#3620]
### Describe your suggested feature

I'd like to have a force landscape setting to use on a Chromecast with Google TV - as LibreTube opens in portrait right now even with "Auto-Rotate" enabled.

### Other details

Quoted previously Closed issue:

> ### Describe your suggested feature
> Great app, but when I installed it on my Samsung Galaxy tablet and my ChromeCast TV stick, it only shows in portrait mode. Could a landscape mode be introduced for those use cases?
> 
> ### Other details
> _No response_
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> * [x]  I have written a short but informative title.
> * [x]  I will fill out all of the requested information in this form.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by voidplayer** [comment]
This has been discussed on #2169

I agree that landscape is the default view on tablet so is very awkward to use it while having to to rotate the tablet every time a video ends

I have no idea how android layout works, but I wonder if its possible to use an adaptative layout like a website instead of a separate layout so you dont have to add features twice

**Comment by Theblackcat98** [comment]
> This has been discussed on #2169
> 
> I agree that landscape is the default view on tablet so is very awkward to use it while having to to rotate the tablet every time a video ends
> 
> I have no idea how android layout works, but I wonder if its possible to use an adaptative layout like a website instead of a separate layout so you dont have to add features twice

Hi Voidplayer, 
I read the issue you tagged. It does not talk about the issue I posted.
I'm not requesting any new landscape buttons or views; I'm asking for a force landscape switch.

**Comment by leberschnitzel** [comment]
Another reason why this would be a great standard option to have:
https://konstakang.com/devices/rpi4/LineageOS20-ATV/
there's now Android TV LinageOS releases that would benefit a lot from a LibreTube that works in landscape (even if other TV settings might not be supported)
I tried it yesterday and there seems to be no way to switch into landscape mode, while the app works great otherwise.

**Comment by Theblackcat98** [comment]
> Another reason why this would be a great standard option to have: https://konstakang.com/devices/rpi4/LineageOS20-ATV/ there's now Android TV LinageOS releases that would benefit a lot from a LibreTube that works in landscape (even if other TV settings might not be supported) I tried it yesterday and there seems to be no way to switch into landscape mode, while the app works great otherwise.

Great review, that explains better what I'm trying to achieve :)

**Comment by diybateriaslifepo4** [comment]
I just installed it on an Android tv and I also have the problem that the Principia screen appears in portrait mode, and I can not force the landscape mode, any solution?

**Comment by SajalRG** [comment]
Hi,

So currently enabled auto-rotation by default in TV. Not sure if that's enough to handle all TV cases, but my tests were fine with emulator.
Please review https://github.com/libre-tube/LibreTube/pull/3838
