### ISSUE TITLE
Sort results by upload date

### ISSUE THREAD

**Issue by popogomo** [libre-tube/LibreTube#3682]
### Describe your suggested feature

Hi guys,

NewPipe, AnimePipe and all other alternative YT clients allow to sort search results by upload date which is very, very handy when searching for videos about specific topics. 

Can you please implement this feature in LibreTube too? Thanks.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
NewPipe doesn't allow this, the extractor doesn't yet allow it.

**Comment by FireMasterK** [comment]
That doesn't really matter. We use the extractor from https://github.com/TeamNewPipe/NewPipeExtractor, along with some minor changes in a fork. We will need to wait for https://github.com/TeamNewPipe/NewPipeExtractor/pull/904 to get merged. We can't really use these changes directly due to the constant merge conflicts that occur when new things are added upstream, it's just way too difficult to maintain.
