### ISSUE TITLE
Add button to close/minimize audio mode

### ISSUE THREAD

**Issue by Flashwalker** [libre-tube/LibreTube#3687]
### Describe your suggested feature

Enhancement: Ui: add unambiguous and obvious button to close/minimize the audio player (not close the playing at all).

### Other details

(System back button doesn't close it.)

If you tap the system back button - you are switch tabs.
If you swipe down - you decrease the volume (or accidentally hit the rewind track)

For now the only way you close the audio mode player is accurately swipe at the edge of the screen or a title - it's not userfriendly UI/UX.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Flashwalker** [comment]
If you tap the system back button - you are switch tabs.  
If you swipe down - you decrease the volume (or accidentally hit the rewind track)

For now the only way you close the audio mode player is accurately swipe at the edge of the screen - it's not userfriendly UI/UX.

**Comment by Bnyro** [comment]
I don't see a place for this in the current UI.

**Comment by FireMasterK** [comment]
I think we could add something on the top left since we don't utilize that space currently. It's also like that on YouTube Music, Spotify, and many more music applications I assume.

Here's a screenshot from the YouTube Music application:
<details>
<img src="https://user-images.githubusercontent.com/20838718/235424029-02aa7b59-60ba-4175-b647-f3684f2b07b1.png" />
</details>

**Comment by Bnyro** [comment]
The button exists now, issues with the audio player are tracked at #3578
