### ISSUE TITLE
Ability to hide shorts

### ISSUE THREAD

**Issue by frmayall1978** [libre-tube/LibreTube#3836]
### Describe your suggested feature

Ability to hide shorts may be a good feature, as I caught myself on just ignoring them upfront, and I'm sure many (not all) people did too. Shorts may sometimes be as annoying to see in the feed as ads.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You can already filter them out inside your subscriptions feed. Hiding them in other parts of the app is not planned.

**Comment by iwannet** [comment]
If we can do it there, why not everywere cuz you  said it was due to api. But we can sort it in the sub feed ??

**Comment by Bnyro** [comment]
The feed API returns all videos at once, while the search API or others don't and only return 20 videos.

**Comment by ebanDev** [comment]
That would definitly be a good feature ✨

**Comment by flexxxxer** [comment]
In my case this feature helps to keep my head out of slop. Most shorts are slop, so hiding them for me lets say necessary. Currently, I'm running LibreTube as local build with shorts hidden and see no drawbacks.

This issue number 25 if you sort issues with total reaction descending and **number 4 in issue list with status not planned**. Also, this issue received few duplicates... So I sent #7969 with implementation. As far as I understand, this and all features with customization goal closed as not planned due to considered to be development burden, see https://github.com/libre-tube/LibreTube/issues/2206#issuecomment-1336186749 for more detailed explanation.

Because of features with customization considered development burden I planning to make my own "fork" (more like upstream + patches) where this and other features will be implemented and shipped. For me implementing #7969 took like 15 minutes (take in mind that I saw code first time), for few other features in issues list it was 10-20 minutes. Upstream can keep doing best what they can, me and other users will got some features outside of LibreTube itself.

Still, I hope devs will reconsider status of this issue and take approach to implement it because it needed by users (number 4 in issue list with status not planned and few created duplicates). If implementation in #7969 considered or will be considered as not fully working because it does not taking subscriptions feed option in scope - I can fix that and send new PR.

**Comment by FineFindus** [comment]
Best of luck with your fork!

**Comment by flexxxxer** [comment]
Everyone is welcome to use [FlexTube](https://github.com/flexxxxer/FlexTube) where ability to hide shorts is available. FlexTube is LibreTube with few changes, so user experience pretty close.

Notice: Bnyro [allowed](https://github.com/libre-tube/LibreTube/discussions/8168#discussioncomment-16308171) to mention FlexTube in issues being addressed by FlexTube

**Comment by ghost** [comment]
I really hope this is re-considerd as AI slop has become much worse and is largly spread through YouTube shorts. There are also scientific papers showing that short-term videos like TikToks, reels and YouTube shorts negatively impact your attention span and make you addicted to them. Since providing a distraction free program is important, I feel this would align. Sponsorblock and DeArrow similarly minimize distractions.
