### ISSUE TITLE
Filter the subscriptions tab by livestreams

### ISSUE THREAD

**Issue by cris0899** [libre-tube/LibreTube#3850]
### Describe your suggested feature

Since I use YouTube mostly to watch liveatreams I think it would be great if you could filter your subscription tab to show only livestreams like you can do in the official YouTube app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Are livestreams in the feed currently marked as live?

**Comment by FireMasterK** [comment]
> Are livestreams in the feed currently marked as live? I haven't been able to find any livestream to test it with.

Yes, they do! But, live streams don't currently show up on the feed unless they are federated through the matrix network or a user clicks on them manually from a channel page/search/directly.

Essentially, the new livestream discovery mechanism is broken (Either due to NewPipeExtractor or a PubSub issue) :/
