### ISSUE TITLE
Make Shorts Vertical in auto rotation (device auto rotation for rotation of the video yk?)

### ISSUE THREAD

**Issue by HageFale** [libre-tube/LibreTube#3934]
### Steps to reproduce

1. Go to a settings make enabie auto rotation.
2.  go to a short and it have big fucking black bars on the side.

### Expected behavior

make the bars on the side away make it vertical and zooming and streching it to the device hight come on you need to test the app not on the computer becausr there a the shorts allright but on the mobile device i cant see the shorts with my eyes im too high.

### Actual behavior

it have big fucking black bars in short i cant get it vertical

### LibreTube version

0.15.0

### Android version

Android 12 MIUI

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by luckkmaxx** [comment]
1. Im not sure what do you mean. Shorts are working well in mobile, You can see them in any orientation without issues. In vertical you will see black space at top and bottom because surelly your device screen ratio is 18:9 or larger, so if you want to fill the whole screen just zoom in with your fingers. If this is not your issue maybe a screenshoot would help.
2. Please dont be rude with your words. Thats unnecessary, and goes against the rules to participate.

**Comment by luckkmaxx** [comment]
Ok I guess this is the issue:

If you are using LibreTube in horizontal orientation (navigating through the feeds, list and so. Maybe a tablet) You are fine with normal videos, because they are yet it horizontal. 
But if you try to play a short being in horizontal, and then you turn your tablet in vertical, the app will exit fullscreen to play in normal mode. So you need to open shorts being in vertical.
I could record the screen if you need.
Anyway there is no confirmation by OP.

**Comment by jrstev** [comment]
I believe I am facing the same issue. When auto-full screen is enabled, there does not seem to be a way to get shorts to go Fullscreen vertically. Attaching screenshots for reference. I have a video but will have to upload it and link it as the file is too large.

![Screenshot_20230621-135426.png](https://github.com/libre-tube/LibreTube/assets/39342803/2b9aa5e0-5de1-4d3d-b7be-55a61a555513)

![Screenshot_20230621-135443.png](https://github.com/libre-tube/LibreTube/assets/39342803/d37034ec-8196-4504-ae18-ad3043e0db44)

![Screenshot_20230621-135451.png](https://github.com/libre-tube/LibreTube/assets/39342803/3ce2d795-869f-442f-95f9-bf9d5d459c11)

**Comment by luckkmaxx** [comment]
if you slideup the video when on vertical, doesnt it goes fullscreen vertical?

**Comment by Bnyro** [comment]
@jrstev That's unfortunately not possible. When we enable auto rotation, the device takes control of the video rotation and we can't make choose the orientation ourselves. Therefore it's only possible when auto full screen is disabled.
Closing due to o rsponse from OP.

**Comment by HageFale** [comment]
right like that

luckkmaxx ***@***.***> schrieb am Mi., 21. Juni 2023, 20:12:
