### ISSUE TITLE
Show full web link in video description

### ISSUE THREAD

**Issue by MatsG23** [libre-tube/LibreTube#3995]
### Describe your suggested feature

In the video description, links that the creator pasted are cut off after specific number of letters (links end with three dots). It would be really helpful to see the full link in the description. The most distinguishable part of a a link is in general the end. It is annoying if there are lots of links/sources in the video description and you cannot find the right one without opening every link.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Gabs-Unk** [comment]
good idea

**Comment by Gabs-Unk** [comment]
or maybe a button to expand it
like "more info"

**Comment by heartlog** [comment]
> ~~or maybe a button to expand it like "more info"~~
## main problem

While holding URL(in description) instead of  FULL URL, only wrapped URL is selected and can be copied. So, maybe you can try using pop-up just like share interface ?

---
Maybe like this -
On hold => open popup prompt with link and copy link
Ex.
On hold of `https://GitHub.com/exampleurl/file...` url
| Url : https://GitHub.com/...| |
| - | - |
| `Full preview on/off switch` ||
| Open URL | Copy url |

**Comment by Bnyro** [comment]
Android text views automatically truncate the text of a link to a certain amount of characters and unfortunately I'm not aware of a way to prevent that. However I think that the focus should be on more important things and therefore close this issue.
