### ISSUE TITLE
Import watch history from Newpipe

### ISSUE THREAD

**Issue by iamtalhaasghar** [libre-tube/LibreTube#4029]
The title.

**Comment by Bnyro** [comment]
NewPipe can't export it.

**Comment by iamtalhaasghar** [comment]
Yes it can. 
Newpipe > Settings > content > export datbase.

This database is a zip file and it contains two sqlite db files. But we aee interested in `newpipe. db` as it has a history table which contains watch history and would be owsm if we can import that in libretube.

My friendship ended with newpipe and libretube is my new friend. 😎

I have written a parser to extract watch history from newpipe db export and it can be found here.
It converts watch history to a format accepted by freetube desktop client. But libretube doesnt have this option in gui. I can write a same parser to help this feature get implemented.

**Comment by iamtalhaasghar** [comment]
@Bnyro

**Comment by Bnyro** [comment]
As long as there is no dedicated format for the watch history NewPipe can export, there are no plans from our side to allow importing it. Extracting data from a database file is out of scope for the project.
However, you can modify your Python script to use the format we use for creating app backups, so that you can import these.
