### ISSUE TITLE
Change the parameters on which videos are marked as watch

### ISSUE THREAD

**Issue by StrangeSam99** [libre-tube/LibreTube#4032]
### Describe your suggested feature

The last update introduced the "mark as unwatched" as an option selectable longpressing videos also in subscription view.
Until now, I used to use the "mark as watched" in combo with "hide watched videos from feed" option enabled to keep clean my feed view from videos I didn't want to watch or from videos I watched, but for example in which I came back to a point just before closing the video (situation where the video stays in the feed because the last position before closing was under 90%).
With the introduction of the "mark as unwatched" option, everytime you open a video from the feed, also if just for for a second, the app switch the option from "mark as watched" to "mark as unwatched", so it's now impossible to remove the video from the feed. The only way to do this is to open the video and manually go to the end, and then closing.
I don't know is this situation is a Bug or was intentionally made, but I ask you to partially revert to fix this thing.
Sorry for my bad English

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Videos are currently marked as watched when they are watched 90%+, and I didn't yet have issues with that.
Restoring the old behavior as suggested here is not planned, you can just first mark the video as watched and as unwatched afterwards then.

**Comment by jakeogh** [comment]
Currently, once the video is watched for even a second, the only option is "Mark as unwatched", so there is no way to "Mark as watched", and therefore (confusingly) the video stays in the subscription feed. It's gotta be a bug, because there is no way to watch a video for a moment, and then decide to "Mark as watched" to remove it from the subscription feed.

As it is currently, the video the user decided to not watch cant be removed from the subscription feed if they watched any portion of it. 

This new to the current release; the previous release lets the user watch a video partially and then "Mark as watched" to remove from the subscription feed.
