### ISSUE TITLE
Ramdom instances option + Test instance

### ISSUE THREAD

**Issue by wuniversales** [libre-tube/LibreTube#4037]
### Describe your suggested feature

Very simple, just add an option to connect randomly to any instance.
Not only would it provide more anonymity, it would also reduce the load on the different instances.

It would also be nice to switch instances in case the randomly selected one fails.

On the other hand, it would also be nice to automatically test the operation of the chosen instance and show the result.

Regards

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
> Very simple, just add an option to connect randomly to any instance.

Nope, each instance is located in a different geographic region, randomly choosing an instance would definitely affect the video quality due to speed loss over long distance. 

> Not only would it provide more anonymity, it would also reduce the load on the different instances.

I answered this part here  https://github.com/libre-tube/LibreTube/issues/3725#issuecomment-1537487947

> It would also be nice to switch instances in case the randomly selected one fails.


https://github.com/libre-tube/LibreTube/issues/3924 

> On the other hand, it would also be nice to automatically test the operation of the chosen instance and show the result.

You can check the instance uptime on piped, pinging instances from LT would put unnecessary load on the servers due to large amount of users. 
https://github.com/TeamPiped/piped-uptime

**Comment by FireMasterK** [comment]
Hi, the Instances API used in the app already tests instances.

**Comment by qokrb2t** [comment]
_Nope, each instance is located in a different geographic region, randomly choosing an instance would definitely affect the video quality due to speed loss over long distance._

The app could get the region. It already does at settings->general->region

_Regarding the load balancing, ye it's good, but you can't just force users to use instances of your choice, especially if the available ones are in a far location.
(anonymity part)_

No need to force a user. Give an alternate option where the app can select instance based on region automatically
