### ISSUE TITLE
Fallback to Piped Proxy Option

### ISSUE THREAD

**Issue by ehea617** [libre-tube/LibreTube#4038]
### Describe your suggested feature

An option under Audio and Video > Advanced that ties in with the "Disable Piped proxy" option. When "Fallback to Piped proxy" is enabled, LibreTube will first attempt direct connection to YouTube. Then if the playback fails, attempt connecting using the selected Piped instance.

This should allow YouTube Music content to load successfully without needing to manually switch back on the Piped proxy and would provide a good mix of speed to load content and less videos that fail to play back.

### Other details

The option can be greyed out if "Disable Piped proxy" is not enabled and checked off by default after enabling "Disable Piped proxy"

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
How would you know that the connectivity issue is solely with YouTube and not with everything else (playing a video without internet connection)? Because this will trigger the fallback to piped proxy you're asking for.

There's no way to do so unless LT pings YouTube and some other website to check the http response code before making a decision. 

In case the check is to be implemented on app launch, if there's an issue with YouTube then you'll have to restart the app to switch to piped. 

In case it's to be implemented on video playing, that's a waste of network bandwidth due to continuous pinging to external servers, not to mention that you might get rate limited (also pinging piped instances isn't an option for obvious reasons because it'll spam the instances with requests) 

Not to mention that the selected instance in the "fallback" thingy could be down or unavailable, which means the videos won't load at all without you going to settings and selecting an instance. 

Not sure if it's because me overthinking, but it's just not practical with little benefit as the majority over here use libretube because of the proxying of requests and only a small fraction (when compared with piped instances users) disable the proxying. So idk lol

**Comment by Bnyro** [comment]
As already said, we can't really tell what the issue is when the player doesn't play. It could also just be a issue with the current network speed and continue playing normally after waiting a short amount of time. If we switched to a Piped instance in that case, that could probably make it even worse.

**Comment by ehea617** [comment]
I just did a network capture using Burp Suite to see if there is something that can be done to detect when this fails.<host>.googlevideo.com responds with HTTP 403 Forbidden for YouTube music videos when the the piped proxy is disabled. All I'm asking is for an option that will attempt to send traffic to the piped proxy only when this connection to googlevideo.com fails with 403 Forbidden for video playback.

**Comment by ehea617** [comment]
Here's an outline of the process:

Scenario 1. User has both Disable Piped proxy and Fallback to Piped proxy enabled
User navigates to a video > LibreTube reaches out to Piped API for video info > LibreTube reaches out to YouTube to begin playback > YouTube (*.googlevideo.com) Responds back with HTTP 403 Forbidden > LibreTube attempts playback through the user's selected piped proxy

Scenario 2. User has Disable Piped proxy enabled and Fallback to Piped proxy disabled
LibreTube behaves as it does currently with the Disable Piped proxy option. Possibly an error message can be presented to the user informing that playback has failed due to the 403 error.

Scenario 3. User has both Disable Piped proxy and Fallback to Piped proxy disabled
LibreTube behaves as it does currently with Disable Piped proxy disabled

**Comment by Bnyro** [comment]
Can you provide a YT music video that doesn't work? I couldn't find any to test it.

**Comment by Bnyro** [comment]
Or please test https://github.com/libre-tube/LibreTube/actions/runs/5314809537

**Comment by ehea617** [comment]
I should specify that by "YouTube music video" I was referring to videos in the YT Music Songs filter on LibreTube's search and not music videos.

Here's the song I used to test that does not play back on LibreTube 0.15.1 with Piped proxy disabled: https://www.youtube.com/watch?v=nyuo9-OjNNg

There appears to be a regression compared to 0.15.1 where these videos are now redirecting to different videos immediately, irrespective of the piped proxy options set.

https://github.com/libre-tube/LibreTube/assets/12926544/05dc71d6-3793-496b-9f44-71c4fc4480b3

**Comment by Bnyro** [comment]
Seems like it thinks the video already ended because we're starting playback asynchronously, which causes it to automatically play the next video (when autoplay is enabled). Weird.
