### ISSUE TITLE
Add option to fullscreen player of all video types

### ISSUE THREAD

**Issue by ticklemyIP** [libre-tube/LibreTube#4083]
### Describe your suggested feature

There is an option for vertical Shorts videos to auto fullscreen I would like to ask for an option of this for regular videos as well.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
What's the purpose of this? Wouldn't it be sufficient to enable "Auto full screen" in the player settings and just rotate the device?

**Comment by ticklemyIP** [comment]
Sure but this could save time if some one doesnt want to enable auto rotate (bad sensors or finds it annoying whatever). This is only worth implementing if the video orientation rotates automatically at the time of full screening to either way. At this point the sensor could be working to determine correct way. It skips the having rotate the device to enter the fullscreen step. And if Shorts videos have this, why couldn't regular videos as well. :P I get this is a bit of a nieche thing.

**Comment by Bnyro** [comment]
I honestly doubt more than a handful of people would use that option, so not planned.

Please only open issues that can be considered useful for the average user, not only about 0.1% of the users.

**Comment by ticklemyIP** [comment]
I think that's way too subjective to determine.

**Comment by kmantel** [comment]
I think this is less niche than you think. Newpipe supports auto fullscreen to landscape orientation always (in fact the reason I found this project is because I couldn't seem to get newpipe to go portrait fullscreen ever, and libretube can). I often hold my device in a way that makes it decide I'm in portrait orientation when I still am watching landscape. 

Entering full screen manually does what I want (chooses full screen orientation based on video orientation not device orientation), and I'd like to be able to set this behavior but also enable auto fullscreen.
