### ISSUE TITLE
Add separate grid column preference for landscape mode

### ISSUE THREAD

**Issue by luckkmaxx** [libre-tube/LibreTube#4186]
### Describe your suggested feature

Im not sure about this in tablets, but for mobiles, its impossible to use the app in landscape, since everything is too zoomed.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Yes libretube isn't well optimized when in landscape mode and as you've mentioned, everything is extremely zoomed.

I do believe this would be a low priority and doubt that project maintainers would work on it as although it's easy to do, but it requires way too many changes and fixes (fixes for awkward behaviors, for example open the search page in landscape, the search bar occupies only half of the screen and the kebab menu would be behind the keyboard) and it's time consuming to reactor.

**Comment by Bnyro** [comment]
related: #3198

No plans to implement that from my side since I don't have a large screen device using Android.
If I should ever buy one, I'd work on this, but this is very unlikely in the near future.

**Comment by terminal-cs** [comment]
> related: #3198
> 
> No plans to implement that from my side since I don't have a large screen device using Android. If I should ever buy one, I'd work on this, but this is very unlikely in the near future.

You don't really even need a big screen device, the issue also seems to happen on normal devices (for the people who even use the feed in landscape anyways...)
You can also test with the android emulator, it lets you simulate tablets

**Comment by shadow-identity** [comment]
It's ok that you guys don't have time and this is not in your priorities to make a landscape UI with a quality you want to have, nobody can shame you for that. 

What could be made easily and improve UX of your amazing app significantly is to make the app to not lock itself in the portrait mode, when device is switched to a landscape. Even if the landscape is not optimized, even if it is not really comfortable. Just let users decide if they want to see it in landscape.

Because the problem is that tablets are used mostly in landscape, standing on a desk or so. It is so annoying to rotate such a big device every time you want to go to the full screen mode and back.

Please, just don't lock the app in portrait. The rest can wait.

**Comment by Bnyro** [comment]
You can always open a PR.

**Comment by luckkmaxx** [comment]
Maybe could be set an option in Settings > Appearance > Grid columns (landscape). To show your prefered number of columns (maybe 3, 4) when the device is in horizontal.

This maybe could be done with Library, and other tabs.
Im not sure the amount of work this could give you (any dev), but this could be a good option. Feed tab looks great with 3 or 4 columns, not for portrait mode.
