### ISSUE TITLE
Passcode/biometric lock 

### ISSUE THREAD

**Issue by DecemberGiraffe** [libre-tube/LibreTube#4245]
### Describe your suggested feature

It would be great if an app passcode and/or biometric lock could be implemented. This would protect a user's privacy with their watch history and subscriptions.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
This is beyond the scope of the project.
And it's your responsibility to protect and maintain your privacy by setting a strong password, not sharing your phone.....

**Comment by luckkmaxx** [comment]
Hi there! I was looking for a similar issue before posting a new one.
I dont know what exactly mean the OP. Maybe a third party app could do the work if you want to protect the whole app.

In my mind I have another wish:
Since there is no parental rating, I wish to set only the "Feed" and "Playlist" tabs with content for my kids, but the settings must be protected by pin or something (optionally of course).

**Comment by Bnyro** [comment]
A PR for that would likely be merged if it's optional since there's no negative impact for users, however that's nothing the project should focus on / I would implement.

**Comment by luckkmaxx** [comment]
Ok thanks anyway
