### ISSUE TITLE
High battery consumption while being idle

### ISSUE THREAD

**Issue by sebastianstucke87** [libre-tube/LibreTube#4266]
### Steps to reproduce

1. Set background usage to `restricted`
2. Force stop LibeTube
3. Go to bed and check battery stats next morning... 😴🕙

### Expected behavior

Batter usage of LibeTube should be at most 1%.

### Actual behavior

Batter usage of LibeTube is at 18%.

### LibreTube version

0.16.1

### Android version

Android 10

### Other details

> "3 min usage" -> 18% battery drain:
> 
> ![](https://github.com/libre-tube/LibreTube/assets/47354551/6c454f3d-bebd-4a76-94fa-f6f808b50739)

--- 
> ![](https://github.com/libre-tube/LibreTube/assets/47354551/7533bd0f-13ca-4b46-8a92-661f0b5d2e92)

---
>![](https://github.com/libre-tube/LibreTube/assets/47354551/580bfc41-b9f0-4338-9c38-7bbcf51cb500)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by sebastianstucke87** [comment]
Yes, that is the odd thing: I have NewPipe as well, and its battery usage is (correctly) at 0%. I don't have a setting for Adaptive Battery though

**Comment by sebastianstucke87** [comment]
Same thing happend again... No other app on my phone behaves like this! 

How can I access/dump the LibreTube logfiles?

(Btw, phone is not rooted and I always install the APKs directly from GitHub.)

<details>

 <summary>Click for screenshots</summary>

Before going to bed:
> ![](https://github.com/libre-tube/LibreTube/assets/47354551/ff0ea739-c537-4797-b345-07fc95bee789)

---

Next Morning:
> ![](https://github.com/libre-tube/LibreTube/assets/47354551/bb6ab721-12b8-4a06-b5d6-0bac3e845481)
> 
> ![](https://github.com/libre-tube/LibreTube/assets/47354551/a65e7a49-0e45-466e-9cc5-ccadc8394dda)

</details>

**Comment by Bnyro** [comment]
Hello there! Sorry to hear that you're experiencing issues with your device's battery life when using our app. I understand how frustrating this can be.

It appears that the issue you're facing is a device-side issue, rather than a problem with the app. This means that the issue is likely caused by something on your device, such as a software or hardware issue, rather than with our app itself.

Unfortunately, as a developer of the app, there is only so much we can do to mitigate device-side issues. LibreTube is designed to run smoothly on a wide range of devices, but we can't guarantee that it will work perfectly on every device or with every software version.

If you have the possibility to, it probably makes sense to run a software update or change the ROM (at least from my experience), otherwise I don't think there's something I could help you with here.
