### ISSUE TITLE
F-droid repo

### ISSUE THREAD

**Issue by Adithyan007hack** [libre-tube/LibreTube#433]
### Describe your suggested feature

Why don't libretube have an f-droid repo?
The updates arrive much slow in the default f-droid universal repo
as the new pipe has its own repo for faster update 
If there was an f-droid repo the updates could arrive faster right??

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [x] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
we would need a server to host it and that would cost money

**Comment by Adithyan007hack** [comment]
> 

"It is okay I just asked due to curiosity"
I can wait for a few days to receive updates please don't abandon this project

**Comment by Bnyro** [comment]
I still want it to be there :D

**Comment by Nizami20052022** [comment]
I wonder how to find it?😁

**Comment by Bnyro** [comment]
or maybe we can host it on github.io xD

**Comment by Bnyro** [comment]
Actually we can't use github.io, that's how it works https://f-droid.org/docs/Setup_an_F-Droid_App_Repo/
we would need our own server for it

**Comment by Bnyro** [comment]
or we could ask @ IzzySoft whether he could accept us for his repo, his repo updates itself really fast

**Comment by Bnyro** [comment]
But it looks like he only accepts apps that are not on F-Droid yet

**Comment by Adithyan007hack** [comment]
> 

Don't worry bro we will find someone for the server hosting
and I have completed the Malayalam translation as much as I can, and it is now 90% complete

**Comment by Bnyro** [comment]
@Adithyan007hack That's great :)

**Comment by bitplane** [comment]
I haven't checked, but does it need to be always running? It looks like it supports mirrors so should be possible using github actions. Only real question is whether the URLs are expected to be inside each other or it can be a fake directory list with links to releases for each file.

**Comment by IzzySoft** [comment]
LibreTube is already available at F-Droid, so what's the reason you want it in my repo as well? Of course it is technically possible (and there are several other apps listed in both), but I'd like to know the reason. Checking its presence:

```
$ iod shell fda com.github.libretube
LibreTube (com.github.libretube) has 3 packages at main, last one added at 2022-06-09.
LibreTube (com.github.libretube) has 2 packages at archive, last one added at 2022-03-21.
Package Id 'com.github.libretube' not found in 'iod'.
```

it's even updated recently (just 2 days ago).

I have a vague hunch it might be about "really fast updates" whenever you had to work around something YT just broke. But unless you're using reproducible builds at F-Droid (as e.g. NewPipe does), there's no cross-updating possible; users then had to make their choice of source from the start.

That said, if you want to I can of course add LibreTube back to my repo (where it was present until this year's April until it became available at F-Droid itself), metadata are still archived and can be easily restored.

@Bnyro for easy setup of your own repo, if you still want to pursue that path, you can also see my articles on the topic – starting with [Setting up a simple binary F-Droid repo](https://android.izzysoft.de/articles/named/fdroid-simple-binary-repo) (oops, I just see I forgot to translate the [follow-up article](https://android.izzysoft.de/articles/named/fdroid-simple-binary-repo-2) to English).

**Comment by Bnyro** [comment]
@IzzySoft First of all thank you for your answer, I really appreciate your help.
We currently don't depend on the "really fast updates" because we use the Piped proxy, so we depend on them to fix things YouTube breaks. However, we would really appreciate to become part of your repo again if you don't mind since it takes F-Droid usually more than a week to update the app. 
Lastly, I will go through your articles about settings up a repo. It's perfect that they are available in german, it'll make my life a lot easier :D The thing is that we still neither have our own server nor a LibreTube domain so that path will probably take some time.
Greetings and thanks for your help

**Comment by IzzySoft** [comment]
In this case: welcome back to IzzyOnDroid! LibreTube will be available there again with the next sync in less than 4h. As before, I've picked the `armeabi-v7a` as that's the most common architecture (and even understood by v8 and arm64 AFAIK, at least with currently existing devices).

May I suggest a change to your `full_description.txt` by the way? Here's what I've set up with IoD:

```html
<i>LibreTube</i> is an alternative frontend for YouTube. It uses the <a href='https://github.com/TeamPiped/Piped' target='_blank' rel='nofollow'>Piped</a> API to load data and play videos and thus needs no YT account and no Google Services on your device.
```

Basically says the same, but looks nicer and directly links to Piped for reference (and yes, this works with F-Droid as well – only Play might strip the links, but that's of no consequence for a "forbidden app", right? :rofl:)

PS: Per-release changelogs are missing in your fastlane since `versionCode:5`, you might wish to add them again starting with the next release (should you add the current one as well, drop me a note and I pull it manually).

**Comment by Bnyro** [comment]
@IzzySoft Thank you for bringing LibreTube back to your repo.
I applied your suggestions to the full_description and added the missing changelog for the last version, I will start adding them from now on. Thank you for the hints and your help :)

**Comment by IzzySoft** [comment]
Thanks @Bnyro! I've just pulled the changelog (a bit too late for today's sync, but will become visible tomorrow) and also adjusted metadata here to pull fulldesc from your fastlane as well from now on.

**Comment by IzzySoft** [comment]
PS: No need to hurry with your own repo if you're satisfied with the current situation :wink:

**Comment by Bnyro** [comment]
@IzzySoft Wow, your repo also includes the new logo now, that's great. You're really doing a great job helping open source apps to grow and take them off some work, great thanks <3

**Comment by IzzySoft** [comment]
Thanks for your kind words, @Bnyro – that motivates me to keep up doing so :hugs:
