### ISSUE TITLE
Add seek buttons for seeking forward or backward in audio player 

### ISSUE THREAD

**Issue by soymadip** [libre-tube/LibreTube#4330]
### Describe your suggested feature

In The audio player, we have next & previous buttons... 

But we can't seek in current stream like for 5/10 seconds....

So seek buttons will allow us to do that..

### Other details

An example from VLC media player:- 
![Screenshot_2023-07-30-12-29-06-38_4aed3257f278fcf7bfa3abd644e23333](https://github.com/libre-tube/LibreTube/assets/84225810/e903734a-3824-4b60-a39b-3fdbf2a8d57d)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Since the audio mode is meant to behave like a music player, I have been taking a look at popular open source audio players, namely Auxio and Retro Music.

Neither of them allows to skip seconds, presumably because skipping parts of music is not a common thing.

I don't think the buttons would align well in our current audio player layout. Therefore not planned currently, due to a lack of reasons for it.

**Comment by soymadip** [comment]
> Since the audio mode is meant to behave like a music player, I have been taking a look at popular open source audio players, namely Auxio and Retro Music.
> 
> Neither of them allows to skip seconds, presumably because skipping parts of music is not a common thing.
> 
> I don't think the buttons would align well in our current audio player layout. Therefore not planned currently, due to a lack of reasons for it.

I respect your decision but I guess beside the forward/next buttons (inside/after play button) won't look bad, 
And seek buttons are important buttons regardless of Audio or any other player...

**Comment by M00NJ** [comment]
> Since the audio mode is meant to behave like a music player, I have been taking a look at popular open source audio players, namely Auxio and Retro Music.
> 
> Neither of them allows to skip seconds, presumably because skipping parts of music is not a common thing.
> 
> I don't think the buttons would align well in our current audio player layout. Therefore not planned currently, due to a lack of reasons for it.

I have a good reason why this is needed,  so I hope you'll reconsider: The music players you mentioned exclusively play music. LibreTube also plays podcasts and commentary videos. I listen to podcasts regularly and use the audio only mode, because of the bug where the background playback stops, after some time of the screen being turned off. It sometimes happens that I miss or don't understand something and have to go back. Using the Seekbar on a 1,5 h podcast to go back 10 s doesn't work. So I have to switch to video mode, use the seek button there and switch back to audio mode. I definitely think seek buttons in the audio mode would be useful.

**Comment by Bnyro** [comment]
Makes sense, that's a valid point.

**Comment by soymadip** [comment]
> > Since the audio mode is meant to behave like a music player, I have been taking a look at popular open source audio players, namely Auxio and Retro Music.
> > Neither of them allows to skip seconds, presumably because skipping parts of music is not a common thing.
> > I don't think the buttons would align well in our current audio player layout. Therefore not planned currently, due to a lack of reasons for it.
> 
> I have a good reason why this is needed, so I hope you'll reconsider: The music players you mentioned exclusively play music. LibreTube also plays podcasts and commentary videos. I listen to podcasts regularly and use the audio only mode, because of the bug where the background playback stops, after some time of the screen being turned off. It sometimes happens that I miss or don't understand something and have to go back. Using the Seekbar on a 1,5 h podcast to go back 10 s doesn't work. So I have to switch to video mode, use the seek button there and switch back to audio mode. I definitely think seek buttons in the audio mode would be useful.

Thanks man, I guess I am pretty bad at explaining things 😅
