### ISSUE TITLE
Quick actions (swipe left/right) inside feed

### ISSUE THREAD

**Issue by MFlisar** [libre-tube/LibreTube#4363]
### Describe your suggested feature

Inside the feed (abos, the view that shows the new videos of subscribed channels) I can long press a video and select from options like:

* play in background
* add to playlist
* download
* share
* mark as seen/unseen

My desired feature would be to be able to select any of the above options as "quick actions" that are executed when swiping left or right on a video.

### Other details

My use case would be to be able to mark a video as seen (and hide it from the feed) by simple swiping left and to download it by swiping right it - instead of long pressing it and click the corresponding button inside the bottom sheet menu... By adding the ability to select any action as quick action the usage possibilities would be a lot higher than my personal usage of this feature...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Hey, thank you for sharing your idea, I appreciate your input.

However, I decided to reject the swiping gestures for the following reasons:
* Adding too many options for small behavior changes (in this case swiping actions) can clutter the interface, more specifically the preferences. The current design prioritizes simplicity and ease of use, and I believe that adding more options may detract from that.
* Since the options are already available when long pressing the video, some actions would be duplicated which is generally matter to avoid.
* It'd be some effort to implement, and I just don't think it's worth it: all the actions (download, ...) already exist, and they don't take you much more time than swipe gestures.

That being said, I appreciate your interest in improving the app.
