### ISSUE TITLE
Import Playlist is Broken

### ISSUE THREAD

**Issue by qfjp** [libre-tube/LibreTube#4407]
### Steps to reproduce

- Create a json file of any importable format (by hand, or by export)
- Delete all playlists from LibreTube for a clean test
- Import the json file

The playlists will be created, but with some (random subsample?) of the full playlist videos.

### Expected behavior

Each playlist should have the full set of videos contained in the json file.

### Actual behavior

Each playlist has significantly fewer videos than the json file specifies.

### LibreTube version

0.16.1

### Android version

13

### Other details

This appears to be a duplicate of issue #2608, however that has already been marked closed.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
With or without account? Which Piped instance? Would you mind sharing your exported file?

**Comment by qfjp** [comment]
Without an account, I built the json file from the databases pulled from newpipe. The file is attached
[piped_playlists.txt](https://github.com/libre-tube/LibreTube/files/12328760/piped_playlists.txt)

**Comment by Bnyro** [comment]
I successfully imported your playlists with the latest debug version:
![Screenshot_20230813-110159_LibreTube Debug](https://github.com/libre-tube/LibreTube/assets/82752168/6d4ffdc1-1e7e-4db8-9fa2-aedf05f4d057)

There have been some changes since the last release to improve the process, which might explain that.

Please keep in mind that you will need to choose a reliable instance while importing, and that some videos can't be imported due to geo-blocking.
