### ISSUE TITLE
DeArrow setting non-functional (thumbnails/titles not changing)

### ISSUE THREAD

**Issue by matchboxbananasynergy** [libre-tube/LibreTube#4451]
### Steps to reproduce

1. Open LibreTube
2. Go to Settings
3. Go to Sponsorblock
4. Enable the DeArrow setting
5. Go back to your subscription feed and check the videos there
6. Observe that videos that should have a different thumbnail/title (as can be seen in Piped with DeArrow enabled) have not changed at all

### Expected behavior

If a thumbnail/title has been submitted in the DeArrow database, LibreTube shoudl show that, instead of the default one.

### Actual behavior

The setting doesn't seem to change the thumbnail/title of videos at all

### LibreTube version

0.17.0

### Android version

Android 13

### Other details

I have tried to force stop and relaunch the app in hopes that it needed a restart for the preference to kick in, but nothing has changed.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I can't reproduce that for my personal feed. For example, [Why Oppenheimer Deserves His Own Movie](https://www.youtube.com/watch?v=Xzv84ZdtlE0&pp=ygUWaGlzdG9yeSBvZiBvcHBlbmhlaW1lcg%3D%3D) by Versatarium is shown as "History of <Oppenheimer", as provided by DeArrow. It's possible that LibreTube and Piped use different parameters to filter unapproved or downvoted thumbnail and title suggestions.

**Comment by Xtrems876** [comment]
I have the exact same issue except:
Titles and thumbnails are successfully changed by dearrow when you enter the channel video feed, but remain unchanged in the subscription feed.

This suggests the problem is with the libretube implementation.

Example: "The stealthiest tech upgrade - AMD $5000 Ultimate Tech Upgrade" in the subscription feed has that clickbaity title, then when you click on it to play it, it continues to have that title, but then when you then click on the LTT channel logo, it takes you to their channel, where it has the following title: "Building a retro style tech upgrade with $5000 from AMD".
