### ISSUE TITLE
Video cannot start at all

### ISSUE THREAD

**Issue by GsK380** [libre-tube/LibreTube#4480]
### Steps to reproduce

1. Open LibreTube
2. Select any video what you want
3. Result

### Expected behavior

Video should play as well

### Actual behavior

Video do not reproduce a sound and giving a black screen, when trying to do something I've got an error «Source Error»

### LibreTube version

0.17.0 (Github) — 0.16.1 (F-Droid)

### Android version

Android 12

### Other details

Before update 0.17.0 everything was okay, but after update come out so my F-Droid version 0.16.1 of LibreTube just started to give the same behaviour as 0.17.0 from Github with absolutely the same problems, I've tried to use diferent servers, tried to use VPN, nothing worked for me.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Tracked at https://github.com/TeamPiped/Piped/issues/2809.

It's NOT related to the LibreTube update, but rather to breaking YouTube changes.

**Comment by Bnyro** [comment]
Due to YouTube changes, it appears that Piped video proxies are getting IP banned, and hence videos don't play. 
You can work around that by going to settings -> audio and video -> disable piped proxy.
However, please keep in mind that this will lead your phone to directly connect to YouTube's servers and hence a VPN should always be enabled when doing that for privacy reasons.
