### ISSUE TITLE
New library design

### ISSUE THREAD

**Issue by tvnmguy** [libre-tube/LibreTube#4596]
### Describe your suggested feature

New design for library section.

![IMG_20230823_151659](https://github.com/libre-tube/LibreTube/assets/116799295/6b92eced-f9b0-4f08-b6d9-defe326193ab)

### Other details

Add swipe between Watch history, Downloads, and Playlists.

https://github.com/libre-tube/LibreTube/assets/116799295/8921916b-9e6e-4d86-8f58-50dae75d4229

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I'm not a fan of this for three reasons:
1. Users would need to get used to the new design. Imo, the app is matured enough to keep its current UI for user convenience.
2. Such a top bar as in your draft is not part of the Material components and guidelines and hence isn't recommended to be used.
3. The watch history fragment would need to become redesigned then, since it has its own top bar.

Therefore thanks for the suggestion, but we'll stick with the current design for now.
