### ISSUE TITLE
Disable updates checking for F-Droid

### ISSUE THREAD

**Issue by shuvashish76** [libre-tube/LibreTube#4627]
### Describe your suggested feature

This is not a FR rather only a request to disable check updates feature for F-Droid flavour.
Reasons
 1. As mentioned in [readme](https://github.com/libre-tube/LibreTube#differences-to-newpipe) "_If the NewPipeExtractor breaks, it only requires an update of Piped and not LibreTube itself._"
 2. Checked with slightly old F-Droid version 0.17.0, it connects to `api.github.com`.
    i) LT is a privacy focused app and we don't need to connect GitHub _unnecessarily_ doesn't matter what GitHub privacy policy or TOS say.
   ii) If the user choose to install from an App Store then they're expected to update from there as well. Hence update checking should be the job of that app store/client.
  iii) I understand the user needs to click on it for updates but
> _New update available. Click to open GitHub release page._

This doesn't makes sense due to signature mismatch and more confusing for new users with different versions.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Users must manually click the button to check for an update, we don't connect to the API of it automatically.

However, this still makes sense for F-Droid users in order to
1. Get a more detailed changelog than on F-Droid
2. Be aware of new updates earlier than with F-Droid (which can sometimes take up to a week to update)

It's not reasonable to create different flavors of the app just because of that which would cause additional efforts for maintaining the app and changes in the F-Droid and IzzyOnDroid configs for the app, hence not planned.

**Comment by shuvashish76** [comment]
> We don't connect to the API of it automatically. Not reasonable to create different flavors of the app just because of that .

Agreed. If no flavours and we support this API anyway then I think we should support "Notify for new updates" feature (should be disabled by default) so that we maximum make use of it.
Usecase : Those who want auto notification updates but don't use any app store not even Obtanium.
