### ISSUE TITLE
Improve group buttons layout behavior

### ISSUE THREAD

**Issue by luckkmaxx** [libre-tube/LibreTube#4647]
### Describe your suggested feature

1. Instead a checkmark, show a play button to play all feed, instead long pressing. (image attached). I dont know if here is possible to add a button inside a button. Maybe the Play could be triggered when you tap once the already shown group button (wich in fact its the only that will show the ▶️ icon.
2. Right now, the "play group" action plays the current shown group, no matter the group you touch (this would be considered a bug).
3. What could be fine to do with a long press is to show the groups editting popup, and definitelly remove the annoying pencil.

### Other details

![Screenshot_20230827-125932_LibreTube Debug (1)](https://github.com/libre-tube/LibreTube/assets/14180594/6a7024a5-f115-4ae6-84e9-84cc90f983e6)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Hey,
As you might now I'm mostly maintaining this project alone for more than a year now and won't have the same amount of time as now in the future.

Therefore I kindly ask you to open less feature requests and only focus on the important ones. I don't mind critical bug reports, but dozens of feature requests per week are just not possible to handle for me all alone. I also want to give other users the chance to propose changes, and not only a small part of the actual users.

You can consider making a donation in appreciation of my work which I'd be very thankful for, in order to support the development.

Kind regards
Bnyro

**Comment by luckkmaxx** [comment]
You couldnt be most right.
Anyway, my FR are ideas for future considerations, that yes, it should be posted in discussions.
Sorry for the inconvenience. I will be reporting bugs as you request.
Yes, I will considere a donation. It worth every €. And you deserve it too.

**Comment by Bnyro** [comment]
Highly appreciated, thank you <3

**Comment by Bnyro** [comment]
Getting back to the issue:
1. I think that this would cause some UX issues, since it's very hard to tap a small button within another button and generally it's a very bad practice to put a button into an other one.
3. I'm certain this would confuse a lot of users - we should keep everything as self-explaining as possible.
