### ISSUE TITLE
Subtitles have incomplete names

### ISSUE THREAD

**Issue by solimm4sks** [libre-tube/LibreTube#4680]
### Steps to reproduce

Look at the subtitles in this video: https://www.youtube.com/watch?v=GroV8G4Amg8 . On LibreTube they are called: None, English, English, (some japanese characters i cant read). On Youtube they are called: Off, English, English - Neobrane, Japanese (auto-generated).

The ones on the youtube client are much more descriptive.

### Expected behavior

The subtitle (caption) track name is the same on LibreTube as it is on Youtube.

### Actual behavior

It's not. It's less descriptive.

### LibreTube version

0.16.1

### Android version

10

### Other details

I especially have gripes with "English - Neobrane" being turned into "English", since that makes it hard to differentiate between the two English tracks.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://piped.video/watch?v=GroV8G4Amg8 shows the same captions as LibreTube, thus it's either not supported by the Piped backend or the NewPipe Extractor to extract the extended language name.

**Comment by Bnyro** [comment]
I can confirm it's a NewPipe Extractor issue.

**Comment by absidue** [comment]
@Bnyro This is highly likely to be a bug on your side not NewPipeExtractor, so I suggest you reopen this.

On Piped it's because they haven't configured shaka-player to use the label, so it defaults to displaying the name of the language instead, also shaka-player deduplicates based on language and role, which is why it is only showing one of the tracks. (look at the `trackLabelFormat` option, which Piped doesn't set: https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.UIConfiguration)

This is probably a configuration issue on your side too.
