### ISSUE TITLE
Logging in to Piped account no longer possible 

### ISSUE THREAD

**Issue by SameenAhnaf** [libre-tube/LibreTube#4841]
### Steps to reproduce

Try to log in to your Piped account on a new app. Or, log out from previously added account and try again.

### Expected behavior

Logging in to Piped app should be just fine.

### Actual behavior

A prompt like `Username or password is incorrect` shown although same username and password work just fine on official Piped instance.

### LibreTube version

0.18.0

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Works well on my side, tried with adminforge instance

**Comment by meiphoo7-Mae** [comment]
Yeah, that's because the adminforge instance is actually working.
Take a look [here](https://archive.ph/hSIvn), this is a screenshot taken about half an hour ago. According to TeamPiped there are 39 servers of which 23 are up and 16 are down, which means 40% of the network is down.
Now take a look [here](https://archive.ph/m7M1W), this is a screenshot taken when anonymously visiting the kavin.rocks instance. It reports only 12 active instances (including a 'custom' one) while it apparently detects itself as unavailable while it is the biggest instance with more than 150K users.

Moreover visiting https://pipedapi.kavin.rocks/ sometimes, but not always, results in an errorpage from cloudflare claiming there's something wrong with the host while visiting https://pipedapi.adminforge.de always works (so far).
