### ISSUE TITLE
Add "Remove from playlist" option

### ISSUE THREAD

**Issue by NeuroException** [libre-tube/LibreTube#4872]
### Describe your suggested feature

Add a "Remove from playlist" option in the long press menu on a playlist item. 
It currently looks like this, and there is no manual option to remove the video.
![Screenshot_20230930-114124](https://github.com/libre-tube/LibreTube/assets/118199015/f4f1f85d-3fd9-4c6e-bb3e-047a04b694d4)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not possible. We don't have any API route to figure out what playlists a video is part of.
In order to allow such a feature, there would need to be one API request per playlist to figure out if it's part of that playlist.

Also, it's possible that videos exist multiple times in a playlist, which can't be handled by that properly.

Thus, not planned.

**Comment by voidplayer** [comment]
I was about to open this bug. Ive searched everywhere, if this is not a bug, how do i remove a video from a playlist?
