### ISSUE TITLE
App not installed as package appears to be invalid

### ISSUE THREAD

**Issue by zhongkechen** [libre-tube/LibreTube#4876]
### Steps to reproduce

1. Download an APK file for arm64 v8a later than this version  4cef17c  https://t.me/LibreTubeAlpha/11798  from Telegram Libretube Alpha channel
2. Install the APK file

### Expected behavior

APK should be installed

### Actual behavior

The error was shown: App not installed as package appears to be invalid

### LibreTube version

Libretube 4cef17c and later

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Test with nighty builds from here https://github.com/libre-tube/NightlyBuilds and report back.

Also give more information like your device type, architecture....

**Comment by zhongkechen** [comment]
Same with the APK file from GitHub

Pixel 7 - Android 14 UPB5

**Comment by Bnyro** [comment]
@IndusAryan is right, after uninstalling and reinstalling the debug version one time, everything should be back as normal and updates should continue to work for debug builds. We used these version codes so that users know when the build they're testing is from, do that it's easier to fix issues they reported in debug builds, but I guess it was kinda useless.
