### ISSUE TITLE
[FR]: Continue watching in library tab

### ISSUE THREAD

**Issue by Silther** [libre-tube/LibreTube#5025]
### Describe your suggested feature

Please add the list of videos you didn't finish watching (called `continue watching` in the home tab) to the library tab in the same style as `watch history` and `downloads` (show a but saying continue watching and if you click it, it should open a new page with all those videos).

I have hidden the home tab in my app, because I don't want to see the trending videos and everything else (except the `continue watching`) is already in the library tab.

### Other details

![signal-2023-10-22-145435](https://github.com/libre-tube/LibreTube/assets/97352673/0c5c5dfc-1f74-41f2-a2ec-fb3b266e9b32)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
In my opinion we should integrate this with a filter in the watch history, so that there's e.g. a checkbox that is called "only show unfinished videos". A dedicated screen doesn't make much sense.

You can work on this if you want to (should be easy), but I don't really see the need to keep the issue open because it wouldn't be addressed without your contribution.
