### ISSUE TITLE
Automatic fullscreen doesn't respect androids lock orientation setting

### ISSUE THREAD

**Issue by Kiisu-Master** [libre-tube/LibreTube#5192]
### Steps to reproduce

1. Turn on automatic fullscreen in libretube 
2. Turn on lock orientation (or turn off automatic rotation) in android settings
3. Play video and turn device

### Expected behavior

Nothing happens

### Actual behavior

App rotates and video goes fullscreen

### LibreTube version

0.20.0

### Android version

Android 11

### Other details

I think the behavior in the youtube app is better.
It doesn't have a automatic fullscreen setting and just uses the device orientation and respects lock orientation( automatic rotation ) setting.

Not using automatic fullscreen doesn't work either as then it minimizes the player when rotating (maybe a bug).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We're already using the sensor orientation when auto fullscreen for the player is enabled. See https://github.com/libre-tube/LibreTube/blob/4d577d463f0a6b9b201cc1498dd54960895f1d5d/app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt#L1393. If that doesn't work, that's due to Android or the ROM, but there's nothing else we could do. And obviously auto rotation doesn't work when the device has it disabled.

**Comment by Kiisu-Master** [comment]
I think you misunderstood the problem. Also it cant be due to Android because the youtube app has no problems with this.

**Comment by d4f5409d** [comment]
Yeah, I experience the same issue, NewPipe seems to work with it quite alright. They mean when we locked rotating in Android, LibreTube still automatically rotates the screen no matter what

**Comment by Kiisu-Master** [comment]
@Bnyro Please re-open this issue.
You closed it without understanding what I said :/ .
