### ISSUE TITLE
More options for links

### ISSUE THREAD

**Issue by gustav-langer** [libre-tube/LibreTube#5225]
### Describe your suggested feature

The only way to access links in places like the description is by clicking on them. It would be really nice if you could, for example, long press a link to actually copy the URL instead of the link text. Maybe you could also have specific options like "save to playlist" for youtube links.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
> The only way to access links in places like the description is by clicking on them
>
That's not the case, the video description is selectable so that you can long press the text around the link and adjust the selection to copy or share the text.

It's such a niche feature that it's not worth implementing, the average user only very rarely wants to do any extra actions with links in the description. More code -> more work to maintain
