### ISSUE TITLE
Strange placement of subtitles

### ISSUE THREAD

**Issue by DanielProg39** [libre-tube/LibreTube#5306]
### Steps to reproduce

1. Open a video
2. Enable subtitles

### Expected behavior

They should display in the centre, or as specified in system settings:
![Screenshot_20231207-134156_Trebuchet](https://github.com/libre-tube/LibreTube/assets/63293432/f6a1cd8d-2120-44c2-82de-e42656714207)

### Actual behavior

They are displayed in the right side of the screen:
![Screenshot_20231207-133228_LibreTube Debug](https://github.com/libre-tube/LibreTube/assets/63293432/a465decb-3c32-4c12-875f-b63051fecda9)

### LibreTube version

LibreTube Debug 0.20.1 commit 3a576a9

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by RafaelsRamos** [comment]
After careful consideration, I think the best approach is to leave this as is.

By changing the ViewType to _VIEW_TYPE_WEB_ we shifted the control of captions to the captions provider. It is generally a good thing, since they can choose to show captions vertically, place them in a position that does not block important visual content, etc.

To center the captions at all time forcefully (I'm not sure if it is possible - since we would need to tweak the CSS coming along with the captions, and I'm not sure we can access that), would be to no longer support the improved experience that lead to #5284.

Youtube does not center the captions:
<img width="448" alt="Screenshot 2023-12-19 at 17 05 38" src="https://github.com/libre-tube/LibreTube/assets/40279132/28af0785-6241-4ada-bfc2-6f20ac2070b4">

**Comment by DanielProg39** [comment]
> Youtube does not center the captions

At least it doesn't push them to the left or right, covering half the screen. I'm perfectly fine with subtitles not being centred, but aligned to the left or right, while covering most of the bottom and not being almost vertical. TBH, I don't think many creators do properly formatted and aligned subtitles, 99% just provide text with basic punctuation, so I don't think it would be a big deal if some subtitles were displayed with HTML tags while others were displayed normally, because I feel that the way they are displayed now is more likely to irritate those who rely on them and cause more inconvenience than if formatted subtitles were not displayed perfectly.

So, in general, I think it would be appropriate to at least disable "web" subtitles when the "System caption style" option is enabled. Not perfect, more of a temporary solution, but still better than what we have now.

**Comment by RafaelsRamos** [comment]
Fair point. I agree with your suggestion. Maybe adding a setting to enable/disable the feature is a good approach. 

If Bnryo thinks this is the way to go, I would happily address this ticket.

**Comment by Bnyro** [comment]
> Fair point. I agree with your suggestion. Maybe adding a setting to enable/disable the feature is a good approach.
>
That's okay with me, feel free to open a PR for adding the preference (something like "Rich caption rendering" or similar). I guess we should disable the preference by default, so that the default behavior is the one before the PR linked above.

> If Bnryo thinks this is the way to go, I would happily address this ticket.
>
Bnyro* :eyes:

**Comment by RafaelsRamos** [comment]
Perfect, I'll grab the ticket then! 👍 
(Sorry about the tipo)
