### ISSUE TITLE
Facilitate changing instance

### ISSUE THREAD

**Issue by RafaelsRamos** [libre-tube/LibreTube#5479]
### Describe your suggested feature

When new users join, it is unclear what instances will work for them. I suggest we make clear to them that the videos might not be loaded due to the instance and make it easy for them to change it (e.g. through a Snackbar).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
There's already a flag next to each instance, an explanation what is an instance and in addition to the newly added uptime percentage. 

Hence i don't think there should be a change (especially when everything is explained on the first app launch) 

![Screenshot_20240111_154103_LibreTube Debug.jpg](https://github.com/libre-tube/LibreTube/assets/50032603/ed406b89-d61d-4bd3-b5b7-8f62352f11b1)

**Comment by RafaelsRamos** [comment]
Hey akano12 👋 👋 

I agree that the information is there (although a lot of people don't read it). However, for new comers, it is not always easy to navigate through it. They just arrived on the App, a look of things to learn. I propose that we guide them, into a working instance. What I propose is something along these lines:

https://github.com/libre-tube/LibreTube/assets/40279132/e8da59ae-13f1-4f6e-82fe-69c891df80f7

**Comment by akano12** [comment]
> Hey akano12 👋 👋 
> 
> I agree that the information is there (although a lot of people don't read it). However, for new comers, it is not always easy to navigate through it. 

1. It's their fault for not reading. 
Also It's not the devs job to spoonfeed everybody, there are tens of thousands of active LibreTube users and i haven't seen anyone asking how to switch an instance.

2. How would you know if an instance isn't working? (I'm aware of couple of ways, but asking in the approach you took)

**Comment by RafaelsRamos** [comment]
I haven't yet dived into that; in the sample, I just added a timeout of X seconds to the requests. If you could share those ways it would be great 💪

**Comment by akano12** [comment]
> I haven't yet dived into that; in the sample, I just added a timeout of X seconds to the requests. If you could share those ways it would be great 💪 

I truly find there's no optimal way to do this.

1. Simplest one would be checking response code received from the instance on app startup, when switching tabs and when doing any action that requires communication with the instance (almost every action in the app).
This will cause a DoS considering the large amount of users (let alone the number of piped web users) and Spotube and whatever front-end apps that use piped instances 

2. The way you did, wait for X seconds timeout. Very impractical on slow networks which could take X+1 seconds to load content.

3. What i suggested in an old issue.

Store currently selected instance in shared preferences, fetch list of available instances on app startup and  check if the selected instance is available in the list of fetched instances. If it's available do nothing, else notify with a toast.


But take it from me, it's better to leave things as is because whatever logic you want to implement, you have to implement it for each action that communicates with a piped instance. Also bnyro briefly summarized why such implementations cause problems more than advantages
https://github.com/libre-tube/LibreTube/issues/3924#issuecomment-1606016522

**Comment by RafaelsRamos** [comment]
Hey @akano12  👋 

Considering your points, I thought about a new behaviour that does not block the loading. It just informs the user that the loading is taking more than it's supposed to, and makes it easier for him/her to change the instance - sample below:


https://github.com/libre-tube/LibreTube/assets/40279132/bc9bcd0a-cba1-459a-9e3c-0dad4c6c9831

That being said, I think the experience is still not great, since the user has no easy way to reload, without the swiping that I did on the second 16.
