### ISSUE TITLE
Imported playlists from CSV don't contain all avaliable videos, and subsequent imports are inconsistent in video amount

### ISSUE THREAD

**Issue by Lazer01** [libre-tube/LibreTube#5503]
### Steps to reproduce

1. Download CSV file of a playlist (Playlist A) from Google Takeout
2. Import into LibreTube
3. Wait
4. Import of playlist (Playlist B) appears
5. Reimport from same CSV file
6. Second import of playlist (Playlist C) appears

### Expected behavior

All avaliable videos from Playlist A should be contained in Playlist B, as Playlist B is an import of Playlist A.

All videos in Playlist B should be in Playlist C, as both Playlist B and C should be fetching the same videos from Playlist A.

### Actual behavior

Playlist B has does not contain most of Playlist A.

Playlist "A":
![Screenshot_20240116_165359](https://github.com/libre-tube/LibreTube/assets/65929763/84de39b4-c847-411c-9012-fa5f0afa462c)

Playlist C contains a different amount of videos than Playlist B.

Playlist B, C, etc.:
![Screenshot_20240116_165450_LibreTube](https://github.com/libre-tube/LibreTube/assets/65929763/5a22cfa1-e39f-4673-b56e-420e8f229b6c)

### LibreTube version

0.21.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
This happens due to the fact that for each video in the playlist, a single API call is needed to fetch video information that is necessary to save the video into the playlist.

I've removed most concurrency to decrease the chances of the instance not responding which should make things a lot better (and slower) - but we will never be able to 100% fix this issue, as we need to make a lot of single api requests for large playlists.
