### ISSUE TITLE
Current Instance Vanishes Sporadically

### ISSUE THREAD

**Issue by TechD123** [libre-tube/LibreTube#5615]
### Steps to reproduce

1. Set up LibreTube and enjoy the great UX ;)
2. Use LibreTube frequently

### Expected behavior

The app doesn't randomly change the instance list.

### Actual behavior

About once a week the app will open to a blank screen (only navigation bar and top bar visible) with a toast message stating that the instance is borked (but in reality it's not the instance at fault). When I look into the instance list I find that some instances are missing (usually the one that was set and some others) and none is selected. I've confirmed this behavior with adminforge.de and the official Piped instance.

Selecting another instance somtimes fixes the issue, however I've found force quitting (via settings, not swiping the app away) to be more reliable. I can then use the same instance as before; at least for a while.

### LibreTube version

0.21.1

### Android version

Android 14 (also present with Android 13)

### Other details

I think this is separate from #5579, as nothing is loading, not even thumbnails or titles of videos.

As this is a random error, I reckon the easiest path is to handle instance failures more gracefully. A toast message is not ideal for a fatal error like this. How about a dialog that links to instance settings?
However, the instance message sometimes appears while watching a video (due to poor connectivity or the instance actually being poorly maintained etc.). Therefore this dialog should only appear if all of the following conditions are met:

- nothing can be displayed (not even titles of videos)
- upon starting the app

Alternatively, a fallback instance setting could be added.

If you let me know how, I'll try getting logs the next time this occurs.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
> The app doesn't randomly change the instance list.
>
The list of instances is fetched from https://piped-instances.kavin.rocks. If the instance is down, it will be removed from temporarily from https://piped-instances.kavin.rocks and hence is not visible in LibreTube. We could discuss if it makes sense to display the currently selected instance in the instances list even though it's monitored as down by https://piped-instances.kavin.rocks for convenience, but I'm not really sure if that's a good idea.

> About once a week the app will open to a blank screen (only navigation bar and top bar visible) with a toast message stating that the instance is borked
>
This can happen due to DNS caching issues when something about the infrastructure of the selected instance changes, I recommend just clearing the cache of the app in case LibreTube doesn't work while the instance is functional in the browser.
I host my own private instance for half a year now and never had such an issue, it's certainly not common for instances that don't change their configurations (e.g. new node / IP address).

**Comment by atollk** [comment]
> We could discuss if it makes sense to display the currently selected instance in the instances list even though it's monitored as down by https://piped-instances.kavin.rocks/ for convenience, but I'm not really sure if that's a good idea.

I feel like a common solution to this is to display the currently selected instance as grayed out. But I do agree with the issue creator that the current behavior can be confusing.
