### ISSUE TITLE
Back gesture not working

### ISSUE THREAD

**Issue by Ehab-d** [libre-tube/LibreTube#5763]
### Steps to reproduce

1. open a video
2. swipe back gesture

### Expected behavior

To go back like it was in the previous version `0.21.1`

### Actual behavior

Nothing happens. Doesn't go back.

https://github.com/libre-tube/LibreTube/assets/129071698/7864260c-1d1d-4afc-8c6a-714ee80c98dc

### LibreTube version

0.22.0

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by deth69** [comment]
Just updated and ran into the same issue.

**Comment by Ehab-d** [comment]
> Just updated and ran into the same issue.

This is an important issue... I'm surprised it doesn't reproduce with the developer.

**Comment by Bnyro** [comment]
https://github.com/libre-tube/LibreTube/discussions/5716

**Comment by PhrozenByte** [comment]
I can confirm this issue; not the back gesture itself, but #5716, but I assume that it's the same underlying problem. The back button is without any function, just nothing happens when being clicked, as reported in #5716. I'm running MIUI 12.5.6 (Android 11) on a Xiaomi Poco F3.

I switched back to 0.21.1 for now since LibreTube 0.22.0 is basically unusable without a working "Back" functionality.

Should we convert discussion #5716 to an issue, or should this issue be renamed to better match the general issue?

What assistance do you need to debug this issue? I'm no Android dev, so can't help there, but maybe debugging; unfortunately I didn't find any resources on how to do that. Besides, there are some more hints in #5716, not sure whether you saw them yet.

**Comment by Bnyro** [comment]
Could somebody who can reproduce it please compile the app with the lines https://github.com/libre-tube/LibreTube/blob/master/app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt#L520-L522
removed and report if this has any impact?

**Comment by Bnyro** [comment]
(Cc @FineFindus)

**Comment by FineFindus** [comment]
> Could somebody who can reproduce it please compile the app with the lines https://github.com/libre-tube/LibreTube/blob/master/app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt#L520-L522
removed and report if this has any impact?

Can confirm that it solves part of the problem, the player can be minimized, although it does not work for switching from full screen.

**Comment by entropy1453** [comment]
Same issue, Android 8.1, MIUI

**Comment by Bnyro** [comment]
Someone that can reproduce the issue, please test https://github.com/libre-tube/LibreTube/actions/runs/8358515425.

**Comment by FineFindus** [comment]
Tested it, using a fresh build based on the latest master, and it's fixed for me :tada:

**Comment by PhrozenByte** [comment]
Tested the `.apk` from the provided debug build and I can confirm that it works for me, too :+1:
