### ISSUE TITLE
Pause upon leaving the app doesn't work anymore

### ISSUE THREAD

**Issue by Kalytis** [libre-tube/LibreTube#5768]
### Steps to reproduce

1. Activate the setting
2. Leave the app or lock the screen

### Expected behavior

Media should pause.

### Actual behavior

Media keeps playing.

### LibreTube version

0.22.0

### Android version

Android 14

### Other details

Disabling/enabling the setting doesn't help.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
What you are talking about are two different options, please enable both:
1. Player -> Behavior when minimized -> Pause
2. Player -> Misc -> Auto-pause

You have to manually change the 1. if you updated the app from a previous version due to internal changes in the app.

I tested it and both still work as expected when enabled.
