### ISSUE TITLE
Unable to view subscribed channels

### ISSUE THREAD

**Issue by houyan0111** [libre-tube/LibreTube#5791]
### Steps to reproduce

Unable to view subscription channel, keeps loading.
![IMG_20240322_095512](https://github.com/libre-tube/LibreTube/assets/158655653/14c2ca80-3b16-4c9c-833a-9d6f8ee0cbda)

### Expected behavior

Show subscription channels

### Actual behavior

keep loading

### LibreTube version

0.22.1

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment]
Reproducing this issue is a bit tricky.

Here's i was able to reproduce it:

1. Open LT
2. Go to subscriptions tab
3. Tab on the subscriptions

However, if you pull to refresh you won't face this problem until you restart the app. 

https://github.com/libre-tube/LibreTube/assets/50032603/50a198a2-32e0-4d45-840f-99f8b714707c

**Comment by OlafSe1** [comment]
Same issue:
- fresh install
- importing subscriptions from either YouTube csv or NewPipe json
- subscriptions tab loads latest videos from that specific imported subscriptions list
- clicking on subscriptions causes loop like in OP
