### ISSUE TITLE
Change user -autoplays video

### ISSUE THREAD

**Issue by T1-12** [libre-tube/LibreTube#581]
After having watched or paused a video in latest version of libreTube I can change user to check my work (used as a profile for work only). I come back to main user profile and the video autoplays after unlocking.  Assume this is a new bug but easily quashed?

**Comment by Bnyro** [comment]
I don't really see a problem here tbh 😂

**Comment by archroid** [comment]
U meant log out and log in again by another username? If no what does CHANGE USER mean?

**Comment by T1-12** [comment]
I can change user in one plus 7.   Scroll down from top and log in as guest
account on same phone.   When I go back to the account playing the video it
just autoplays from the start.  Not even unlocked the screen

**Comment by Bnyro** [comment]
That's nothing we can influence, that's rather an android issue. I tried the same thing as described with other video/music players and they all crash (e.g. RetroMusic) or start from the beginning again.  And tbh I don't think that's a real problem since it doesn't make sense to switch the account while playing a video.
