### ISSUE TITLE
Playback issues

### ISSUE THREAD

**Issue by Diffuser2574** [libre-tube/LibreTube#5859]
### Steps to reproduce

1. Open any Video

### Expected behavior

Video starts playing

### Actual behavior

Short loading symbol appears and screen stays black.

### LibreTube version

0.22.2

### Android version

Android 12

### Other details

Switching to Audio mode shows a short "Source Error" Pop-Up.
Opening the video within an external player shortly plays the video but then stopps.
Switching Proxy doesn't affect it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by anoo2niem** [comment]
I have the same issue since yesterday.

LibreTube isn't able to play anything, stays on black screen. I've tried fiddling with the settings a little bit & even downgraded the app. The issue remains.

I have my selfhosted instance, so i thought the issue lays there initially. But changing to different instances didn't change anything.

The 'metadata'(title/total time video/chapters/etc) are loading, but the screen stays black and for some reason the quality is always reverted to 0p.

One interesting observation i made; when i switch from dash to hls, on public instances i can play videos. When i revert to dash, black screen again. Hls for some reason don't seem to work in my private instance.

If i can provide some more detailled data regarding this issue, please tell me which and how to obtain it.

**Comment by Bnyro** [comment]
https://github.com/libre-tube/LibreTube/issues/5855
