### ISSUE TITLE
Lack of playlist options and difference between bookmarks and personal playlists

### ISSUE THREAD

**Issue by imetadragon** [libre-tube/LibreTube#5869]
### Steps to reproduce

1- Bookmarked playlists doesn't have **sorting** option. 

2- Bookmarked playlists doesn't have **Mix** option. 

3- Personal playlists doesn't have **delete video** option. If you add a video in playlist, you can't remove it from the list.

### Expected behavior

1- If i want to sort the videos in personal playlists, i can. But i can not do it in bookmarked playlists. 
2- Personal playlists have this feature but not bookmarked ones.
3- Could have been able to delete videos in personal playlists.

### Actual behavior

Explained

### LibreTube version

0.22.2

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
1, 2. Shuffling is only possible for private playlists since we only get 20 playlist items per API call, thus it would result in a very bad UX if we had to fetch all of them first before the first, random video starts loading. The same applies for sorting. Bookmarks are just references to public playlists.
3. Swipe the video/playlist you want to delete to the left
