### ISSUE TITLE
Latest missing on F-Droid

### ISSUE THREAD

**Issue by networxnet** [libre-tube/LibreTube#6113]
### Steps to reproduce

Check for latest release on F-Droid 

### Expected behavior

See latest release on F-Droid

### Actual behavior

Latest release still missing on F-Droid. Not for the first time, so Auto updates not work.

### LibreTube version

0.23

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by DanielProg39** [comment]
It's a question for F-droid maintainers/contributors. Updates can be ship with a delay there, which is normal, but it's been a month since the last update and can be a valid concern. Maybe @licaon-kter can help

**Comment by licaon-kter** [comment]
back, F-Droid can't detect a new version since there's none: https://github.com/libre-tube/LibreTube/blob/v0.23.2/app/build.gradle.kts#L18-L19 @Bnyro 

Do update versionCode (and versionName) before tagging a new version :wink:

**Comment by Bnyro** [comment]
> back, F-Droid can't detect a new version since there's none: https://github.com/libre-tube/LibreTube/blob/v0.23.2/app/build.gradle.kts#L18-L19 @Bnyro
> 
> Do update versionCode (and versionName) before tagging a new version 😉
>
Whoops, I've been a bit stressed while creating that release because 0.23.1 had some ugly bugs I quickly wanted to fix with a new release and apparently forgot to merge my PR with the version code before publishing the release.

Since it probably won't take that long until the next release, we will just continue as usual with that one when it'll be released.

Thanks for the clarification @licaon-kter .
