### ISSUE TITLE
Button to remove watched videos from a playlist

### ISSUE THREAD

**Issue by cyber-sec0** [libre-tube/LibreTube#6226]
### Describe your suggested feature

Either that or when I click on "play all", ignore watched videos and start from the first unwatched video found

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's already possible (with some additional clicks).

Press "Play all" -> open the playing queue (the playlist icon at the top right of the video controls) -> Press the eye at the bottom -> Remove watched videos.

I don't want to add a custom way for playlists to do this because then we'd also need a way to do this as well for any other place where a "Play all" button is present, e.g. the channel page, subscriptions page, ...
