### ISSUE TITLE
Can't watch videos in debug app, login error appears

### ISSUE THREAD

**Issue by DoraTee** [libre-tube/LibreTube#6347]
### Steps to reproduce

1. Enter the debug app 
2. Select any instance
3. Login to an instance
4. Try and play video
5. Error "sign in to confirm you're not a bot" appears
![Screenshot_20240812-195204_LibreTube Debug](https://github.com/user-attachments/assets/efa23c20-0a06-48d7-80c5-48a15f02a60a)

### Expected behavior

When you enter the debug app and login and play a video, the video should play.

### Actual behavior

I enter the debug app and it doesn't allow me to play a video no matter what instance I choose.

### LibreTube version

Debug v 0.24.0

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by GlytchMeister** [comment]
I have been getting this in all instances with the regular app as well

**Comment by GlytchMeister** [comment]
I tried using piped directly and got the same error, and their issues page has this same topic.  Current speculation is that piped instances are getting blacklisted whack-a-mole style by google.  Quickly, too, because its effecting even brand new ones.

Some Invidious instances are using a tool to cycle through IPv6 addresses, but sometimes entire IPv6 ranges are getting blocked.

Sounds like youtube/google is cracking down hard on FOSS frontends.

**Comment by BatDevil** [comment]
> Sounds like youtube/google is cracking down hard on FOSS frontends.

instead of y'know, fixing their hellscape platform that promotes scams, even the CIA said you should use an AdBlocker, that's how bad YouTube is.

**Comment by akano12** [comment]
https://github.com/libre-tube/LibreTube/issues/6116

**Comment by GlytchMeister** [comment]
> #6116

That one is closed, and the last comment says "tldr just change instance", which... Doesn't solve the problem.  All instances are down because of this.  New instances are down.

And according to https://github.com/TeamPiped/Piped/issues/3658#issuecomment-2236961443 , patching getAuthtoken is unrelated, and YouTube API keys don't work, because they'd need to be used in the Piped back end, not just the frontend.  And that's the only speculated solution I've seen that isn't just "lol use a different instance"

They're all blocked.  I just went and tried them all.

**Comment by GlytchMeister** [comment]
Disabling the piped proxy whilst using VPN doesn't solve it either, for what its worth, but I get the distinct impression I'm talking to a wall

**Comment by akano12** [comment]
> Disabling the piped proxy whilst using VPN doesn't solve it either, for what its worth, but I get the distinct impression I'm talking to a wall

Feel free to fix it yourself then, otherwise you can wait for project maintainers to check during their limited free time.

**Comment by GlytchMeister** [comment]
> Feel free to fix it yourself then, otherwise you can wait for project maintainers to check during their limited free time.

There's a difference between acknowledging there is an issue and saying "we'll get to it when we can" as opposed to saying "do this thing that you literally just said doesn't work" and closing the issue.

I fully understand contributors and maintainers have limited time to spend on foss projects.  But telling users to get bent or do it themselves and then putting your fingers in your ears and going "lalalalalala" doesn't exactly inspire confidence and trust.

I've since switched to newpipe.  I don't need to worry about using Libretube's proxy since I have a kill-switched VPN, but up until now, I wanted to support Libretube in what little ways I could because I liked that this project went the extra mile to use a proxy, which made me think the project was more serious about privacy and protecting users from Google's hostile and unethical practices.

I guess I know better, now.  ¯\_(ツ)_/¯
