### ISSUE TITLE
Recommended videos appear to be released in 1970

### ISSUE THREAD

**Issue by Application-maker** [libre-tube/LibreTube#6401]
### Steps to reproduce

1. Disable piped proxy ?
2. Start watching any video

### Expected behavior

Self-explanatory.

### Actual behavior

The recommended videos appear to be uploaded in 1970 (54 years ago in 2024).

### LibreTube version

0.25.1

### Android version

Android 14

### Other details

![Screenshot_2024-08-23-22-34-21-10_54f92cd6866f5233ab0db4392b806878](https://github.com/user-attachments/assets/f29ad46d-35ac-474c-afc5-671fcc21c441)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by MadMan247** [comment]
Can confirm, just experienced, was going to make a bug report. Note all videos in the recommended feed say 54 years.
This certainly has something to do with the new youtube workaround option "local stream extraction", because using a piped proxy (took eons to get one to work) resulted in a proper date.

Local stream extraction:
![Screenshot_20240826_013928_LibreTube](https://github.com/user-attachments/assets/503104a7-3068-4986-b55e-a5544f0283fe)

Piped proxy enabled:
![Screenshot_20240826_014334_LibreTube](https://github.com/user-attachments/assets/da5adf2c-b944-459b-ac83-859f5666d95d)


Immacualte Rick roll btw.
