### ISSUE TITLE
PLAYING ERROR 

### ISSUE THREAD

**Issue by taharimbadhon** [libre-tube/LibreTube#6458]
### Steps to reproduce

(Disable  piped proxy and local stream extraction)  is enabled.When i play videos it plays well for the first 5 to 6 vidros.But somtimes it suddenly shows IOS player responseinvalid or Got error sign in to confirme you are not a bot.    
2.when i turn Libre tube into a audio player it can not change video or audio from the notificatio panel.Over all notification is not working at all

### Expected behavior

1.Expected to play every Video
2.Should change video or audio from notification     

### Actual behavior

1.Not playing videos 
2.Not changing videos

### LibreTube version

0.25..2

### Android version

11

### Other details

I love your work so much.I use only libretube for watching video.I hope i will Donate  to your project soon.Please give your crypto wallet address. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's unfortunately indicating that either yoir IP address is blocked or that there's a new bug in the NewPipe extractor.

LibreTube doesn't implement the extraction logic itself when local streams extraction is enabled, it just usea the NewPipe Extractor.

PS: I was planning to set up a Lightning wallet, but it seemed very complicated at first glance because you have to host your own node, so I gave up on crypto for now.
