### ISSUE TITLE
Volume below 6/100 in LibreTube results in no sound

### ISSUE THREAD

**Issue by clicky6** [libre-tube/LibreTube#6906]
### Steps to reproduce

1. Play any video.
2. Set the volume to 6/100 – sound is audible.
3. Decrease the volume to below 6/100 – no sound can be heard.

### Expected behavior

The sound volume should decrease smoothly and proportionally (like it is with values greater than 6/100), even for very low volume levels, rather than cutting off entirely.

### Actual behavior

The sound stops completely when the volume is below 6/100.

### LibreTube version

0.26.0

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
LibreTube sets the volume via Android's audio manager, see https://github.com/libre-tube/LibreTube/blob/master/app/src/main/java/com/github/libretube/helpers/AudioHelper.kt#L9.

The `Audio manager` uses the volume steps from your phone under the hood. The amount of volume steps and the step size can vary depending on the phone,  and Android's audio manager sets the volume to 0 if no lower possible volume step has been found, thus that's the expected behavior.
