### ISSUE TITLE
Hide Top bar when scrolling up.

### ISSUE THREAD

**Issue by simanchal-45** [libre-tube/LibreTube#725]
### Describe your suggested feature

The sticky top bar should be hide when scrolling up.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We already had issues for that and we came to the conclusion that it's not really possible.
We can hide the toolbar on the top and the bottom navigation, but they get replaced by empty space then and not by the current fragment.
Users wouldn't really benefit from that since there is no extra space won then.
Maybe there is another way to make it work but from my point of view there is none.
