### ISSUE TITLE
Fullscreen Upon Landscape

### ISSUE THREAD

**Issue by neillium** [libre-tube/LibreTube#760]
### Describe your suggested feature

A feature that would be wonderful would be to see the app go fullscreen and exit fullscreen depending on Landscape or Portrait mode once I have started playing the video. Newpipe currently does this particular feature.

I searched for someone having this particular request but could not find anything related. I'd it's a duplicate, my apologies! 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Yes, you're right, that's not a bad idea. The problem is that we currently have an option for auto rotation while in full screen mode so there would be a conflict between these two features, both at the same time wouldn't really work. Feel free to tell me if you have any idea how to solve that conflict :)
