### ISSUE TITLE
Easier way to turn on and off subtitle, plus separate language selector button

### ISSUE THREAD

**Issue by lucamp** [libre-tube/LibreTube#873]
### Describe your suggested feature

With the new 0.4.1 subtitle button has been put under video option menu, requiring one more touch from before to enable or disable subtitles. Nevertheless, even the old method was not quick since you always need to choose the language from a list.

I suggest:

- 1 CC button that just cycles subtitle on or off, near the full screen
- 1 subtitle language selector button, under the video option menu (where CC is now)
- option to choose the default subtitle language under LibreTube settings

In this way, it's easy to turn off and on subtitle for a user that is learning a language but do not want to always read the subtitle and prefer to first try to get new words from the content

Thanks
Luca

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
One reason for me to write the new subtitles dialog was to make setting the default subtitle language possible, I added the setting for it now in #878.

The goal of the Player UI changes was to make the controls take less space to
1. make it look better
2. make them hide less of the video when visible
3. 
That's why I don't think that adding a button to turn subtitles on and off is a good idea, it would
1. just take space we created in the last update
2. be kind of a dupe of the original button

Cheers

**Comment by Taffroi** [comment]
Could it be reconsidered please ? I'm not a native english speaker but I watch a lot of videos in this language and on the YouTube app, I used to turn on and off subtitles all the time between videos of different languages using the shortcut at the top-right of the video.

There are a lot of shortcut buttons I literally never use like the lock button (at the left), the automatic player & the video queue, and honestly I would disable them if I could. I believe these are less useful than subtitles, as you don't need to consult them as often.

Is it possible at least to customize the player buttons to add a shortcut for subtitles? Thx
